// wardrobeConfig.js
export const WARDROBE_CONFIG = {
  // ══════════════════════════════════════
  // FONTS
  // ══════════════════════════════════════

  // Progress (Level-gated)
  scholarly_serif: {
    label: "Scholarly Serif",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 5",
    googleFont: null,
    cssVars: { "--user-font": "'Georgia', 'Times New Roman', serif" },
  },
  jetbrains_mono: {
    label: "JetBrains Mono",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 8",
    googleFont: "JetBrains+Mono:wght@300;400;500",
    cssVars: { "--user-font": "'JetBrains Mono', monospace" },
  },
  space_grotesk: {
    label: "Space Grotesk",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 12",
    googleFont: "Space+Grotesk:wght@300;400;500;600",
    cssVars: { "--user-font": "'Space Grotesk', sans-serif" },
  },
  lora_serif: {
    label: "Lora",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 18",
    googleFont: "Lora:ital,wght@0,400;0,600;1,400",
    cssVars: { "--user-font": "'Lora', Georgia, serif" },
  },
  cinzel: {
    label: "Cinzel",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 30",
    googleFont: "Cinzel:wght@400;600;700",
    cssVars: { "--user-font": "'Cinzel', serif" },
  },
  cormorant_garamond: {
    label: "Cormorant Garamond",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 35",
    googleFont: "Cormorant+Garamond:ital,wght@0,400;0,600;1,400",
    cssVars: { "--user-font": "'Cormorant Garamond', Georgia, serif" },
  },
  bangers: {
    label: "Bangers",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 40",
    googleFont: "Bangers",
    cssVars: { "--user-font": "'Bangers', Impact, cursive" },
  },
  orbitron: {
    label: "Orbitron",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 55",
    googleFont: "Orbitron:wght@400;600;700",
    cssVars: { "--user-font": "'Orbitron', sans-serif" },
  },

  // Progress (Hour-gated)
  typewriter_pro: {
    label: "Typewriter Pro",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "50 total hours",
    googleFont: null,
    cssVars: { "--user-font": "'Courier New', Courier, monospace" },
  },
  playfair_display: {
    label: "Playfair Display",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "100 total hours",
    googleFont: "Playfair+Display:ital,wght@0,400;0,700;1,400",
    cssVars: { "--user-font": "'Playfair Display', Georgia, serif" },
  },
  fira_code: {
    label: "Fira Code",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "150 total hours",
    googleFont: "Fira+Code:wght@300;400;500",
    cssVars: { "--user-font": "'Fira Code', 'Courier New', monospace" },
  },
  dm_serif: {
    label: "DM Serif Display",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "250 total hours",
    googleFont: "DM+Serif+Display:ital@0;1",
    cssVars: { "--user-font": "'DM Serif Display', Georgia, serif" },
  },
  instrument_serif: {
    label: "Instrument Serif",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "500 total hours",
    googleFont: "Instrument+Serif:ital@0;1",
    cssVars: { "--user-font": "'Instrument Serif', Georgia, serif" },
  },

  // Sprints
  retro_pixel: {
    label: "Retro Pixel",
    category: "fonts",
    rewardType: "sprint",
    unlockHint: "20 hrs/week",
    googleFont: "Press+Start+2P",
    cssVars: { "--user-font": "'Press Start 2P', monospace" },
  },
  modern_minimalist: {
    label: "Modern Minimalist",
    category: "fonts",
    rewardType: "sprint",
    unlockHint: "40 hrs/month",
    googleFont: null,
    cssVars: { "--user-font": "'Inter', 'Helvetica Neue', sans-serif" },
  },

  // ══════════════════════════════════════
  // RINGS
  // ══════════════════════════════════════

  // Progress (Level-gated)
  slate_outline: {
    label: "Slate",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 5",
    ringClass: "slate-outline-ring",
  },
  lavender_drift: {
    label: "Lavender Drift",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 7",
    ringClass: "lavender-drift-ring",
  },
  ring_bronze: {
    label: "Bronze",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-amber-700 ring-offset-2 ring-offset-base-100",
  },
  ring_silver: {
    label: "Silver",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-gray-400 ring-offset-2 ring-offset-base-100",
  },
  ring_gold: {
    label: "Gold",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-yellow-400 ring-offset-2 ring-offset-base-100",
  },
  ring_ruby: {
    label: "Ruby",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-red-500 ring-offset-2 ring-offset-base-100",
  },
  ring_sapphire: {
    label: "Sapphire",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-blue-500 ring-offset-2 ring-offset-base-100",
  },
  ring_emerald: {
    label: "Emerald",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-emerald-500 ring-offset-2 ring-offset-base-100",
  },
  ring_amethyst: {
    label: "Amethyst",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-purple-500 ring-offset-2 ring-offset-base-100",
  },
  ring_obsidian: {
    label: "Obsidian",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-gray-900 ring-offset-2 ring-offset-base-100",
  },
  ring_ivory: {
    label: "Ivory",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-stone-200 ring-offset-2 ring-offset-base-100",
  },
  ring_steel: {
    label: "Steel",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-slate-500 ring-offset-2 ring-offset-base-100",
  },
  spectral_shift: {
    label: "Spectral Shift",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 13",
    ringClass: "spectral-shift-ring",
  },
  jade_glow: {
    label: "Jade Glow",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 15",
    ringClass: "jade-glow-ring",
  },
  eternal_flame: {
    label: "Eternal Flame",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 20",
    ringClass: "eternal-flame-ring",
  },
  frozen_crystal: {
    label: "Frozen Crystal",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 20",
    ringClass: "frozen-crystal-ring",
  },
  rose_quartz: {
    label: "Rose Quartz",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 22",
    ringClass: "rose-quartz-ring",
  },
  scholars_glow: {
    label: "Scholar's Glow",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 25",
    ringClass: "scholars-glow-ring",
  },
  copper_coil: {
    label: "Copper Coil",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 28",
    ringClass: "copper-coil-ring",
  },
  twilight_band: {
    label: "Twilight Band",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 32",
    ringClass: "twilight-band-ring",
  },
  ivy_league: {
    label: "Ivy League",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 35",
    ringClass: "ivy-league-ring",
  },
  sakura_ring: {
    label: "Sakura",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 35",
    ringClass: "sakura-ring",
  },
  golden_hour: {
    label: "Golden Hour",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 35",
    ringClass: "golden-hour-ring",
  },
  thunder_strike: {
    label: "Thunder Strike",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 38",
    ringClass: "thunder-strike-ring",
  },
  prism_spin: {
    label: "Prism",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 40",
    ringClass: "prism-spin-ring",
  },
  seafoam_wave: {
    label: "Seafoam Wave",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 45",
    ringClass: "seafoam-wave-ring",
  },
  diamond_edge: {
    label: "Diamond Edge",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 50",
    ringClass: "diamond-edge-ring",
  },
  cosmic_dust: {
    label: "Cosmic Dust",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 50",
    ringClass: "cosmic-dust-ring",
  },
  void_static: {
    label: "Void Static",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 55",
    ringClass: "void-static-ring",
  },
  neon_halo_ring: {
    label: "Neon Halo",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 60",
    ringClass: "neon-halo-ring",
  },
  blood_moon: {
    label: "Blood Moon",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 62",
    ringClass: "blood-moon-ring",
  },
  zen_blossom: {
    label: "Zen Blossom",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 65",
    ringClass: "zen-blossom-ring",
  },
  abyssal: {
    label: "Abyssal",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 68",
    ringClass: "abyssal-ring",
  },
  celestial_orbit: {
    label: "Celestial Orbit",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 70",
    ringClass: "celestial-orbit-ring",
  },
  phantom_drift: {
    label: "Phantom Drift",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 75",
    ringClass: "phantom-drift-ring",
  },
  void_smoke: {
    label: "Void Smoke",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 80",
    ringClass: "void-smoke-ring",
  },
  magma_flow: {
    label: "Magma Flow",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 85",
    ringClass: "magma-flow-ring",
  },
  cyber_neon_pulse: {
    label: "Cyber Neon Pulse",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 90",
    ringClass: "cyber-neon-pulse-ring",
  },
  quantum_flux: {
    label: "Quantum Flux",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 95",
    ringClass: "quantum-flux-ring",
  },
  crimson_tide: {
    label: "Crimson Tide",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 100",
    ringClass: "crimson-tide-ring",
  },

  // Progress (Hour-gated)
  moonbeam: {
    label: "Moonbeam",
    category: "rings",
    rewardType: "progress",
    unlockHint: "25 total hours",
    ringClass: "moonbeam-ring",
  },
  verdant_pulse: {
    label: "Verdant Pulse",
    category: "rings",
    rewardType: "progress",
    unlockHint: "35 total hours",
    ringClass: "verdant-pulse-ring",
  },
  amber_sunset: {
    label: "Amber Sunset",
    category: "rings",
    rewardType: "progress",
    unlockHint: "75 total hours",
    ringClass: "amber-sunset-ring",
  },
  opal_sheen: {
    label: "Opal Sheen",
    category: "rings",
    rewardType: "progress",
    unlockHint: "125 total hours",
    ringClass: "opal-sheen-ring",
  },
  deep_ocean_ring: {
    label: "Deep Ocean",
    category: "rings",
    rewardType: "progress",
    unlockHint: "150 total hours",
    ringClass: "deep-ocean-ring",
  },
  aurora_borealis: {
    label: "Aurora Borealis",
    category: "rings",
    rewardType: "progress",
    unlockHint: "300 total hours",
    ringClass: "aurora-borealis-ring",
  },
  emerald_depths: {
    label: "Emerald Depths",
    category: "rings",
    rewardType: "progress",
    unlockHint: "350 total hours",
    ringClass: "emerald-depths-ring",
  },
  starfield_ring: {
    label: "Starfield",
    category: "rings",
    rewardType: "progress",
    unlockHint: "500 total hours",
    ringClass: "starfield-ring",
  },
  singularity_ring: {
    label: "Singularity",
    category: "rings",
    rewardType: "progress",
    unlockHint: "750 total hours",
    ringClass: "singularity-ring",
  },
  solar_flare: {
    label: "Solar Flare",
    category: "rings",
    rewardType: "progress",
    unlockHint: "1000 total hours",
    ringClass: "solar-flare-ring",
  },

  // Sprints
  overdrive_ring: {
    label: "Overdrive",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "20 hrs/week",
    ringClass: "overdrive-ring",
  },
  neon_circuit: {
    label: "Neon Circuit",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "25 hrs/week",
    ringClass: "neon-circuit-ring",
  },
  electric_pulse: {
    label: "Electric Pulse",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "25 hrs/week",
    ringClass: "electric-pulse-ring",
  },
  grindstone_ring: {
    label: "Grindstone",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "30 hrs/week",
    ringClass: "grindstone-ring",
  },
  persistence_ring: {
    label: "Persistence",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "30 hrs/month",
    ringClass: "persistence-ring",
  },
  marathon_ring: {
    label: "Marathon",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "50 hrs/month",
    ringClass: "marathon-ring",
  },
  titan_ring: {
    label: "Titan",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "70 hrs/month",
    ringClass: "titan-ring",
  },

  // ══════════════════════════════════════
  // OVERLAYS
  // ══════════════════════════════════════

  // Progress (Level-gated)
  snowfall: {
    label: "Snowfall",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 15",
    overlayClass: "snowfall-overlay",
  },
  fireflies: {
    label: "Fireflies",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 22",
    overlayClass: "fireflies-overlay",
  },
  northern_lights: {
    label: "Northern Lights",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 45",
    overlayClass: "northern-lights-overlay",
  },
  star_rain: {
    label: "Star Rain",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 70",
    overlayClass: "star-rain-overlay",
  },

  // Progress (Hour-gated)
  dust_particles: {
    label: "Dust Particles",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "50 total hours",
    overlayClass: "dust-particles-overlay",
  },
  nebula_mist: {
    label: "Nebula Mist",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "100 total hours",
    overlayClass: "nebula-mist-overlay",
  },
  rainy_window: {
    label: "Rainy Window",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "150 total hours",
    overlayClass: "rainy-window-overlay",
  },
  falling_leaves: {
    label: "Falling Leaves",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "200 total hours",
    overlayClass: "falling-leaves-overlay",
  },
  sakura_breeze: {
    label: "Sakura Breeze",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "300 total hours",
    overlayClass: "sakura-breeze-overlay",
  },
  fog_drift: {
    label: "Fog Drift",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "400 total hours",
    overlayClass: "fog-drift-overlay",
  },
  confetti_burst: {
    label: "Confetti Burst",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "1000 total hours",
    overlayClass: "confetti-burst-overlay",
  },

  // Sprints
  matrix_code: {
    label: "Matrix Code",
    category: "overlays",
    rewardType: "sprint",
    unlockHint: "20 hrs/week",
    overlayClass: "matrix-code-overlay",
  },
  ember_storm: {
    label: "Ember Storm",
    category: "overlays",
    rewardType: "sprint",
    unlockHint: "30 hrs/week",
    overlayClass: "ember-storm-overlay",
  },
  crystal_frost: {
    label: "Crystal Frost",
    category: "overlays",
    rewardType: "sprint",
    unlockHint: "80 hrs/month",
    overlayClass: "crystal-frost-overlay",
  },

  // ══════════════════════════════════════
  // NAMEPLATES
  // ══════════════════════════════════════

  // Progress (Level-gated)
  golden_ribbon: {
    label: "Golden Ribbon",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 5",
    nameplateClass: "np-golden-ribbon",
    preview: "Gold gradient with shine effect",
  },
  gothic_parchment: {
    label: "Gothic Parchment",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 15",
    nameplateClass: "np-gothic-parchment",
    preview: "Aged parchment look with serif styling",
  },
  cyber_hud: {
    label: "Cyberpunk HUD",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 25",
    nameplateClass: "np-cyber-hud",
    preview: "Neon blue brackets with HUD aesthetic",
  },
  prismatic: {
    label: "Prismatic",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 40",
    nameplateClass: "np-prismatic",
    preview: "Slow-moving rainbow gradient",
  },
  obsidian_seal: {
    label: "Obsidian Seal",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 60",
    nameplateClass: "np-obsidian-seal",
    preview: "Dark stone border with silver inlay",
  },
  celestial_script: {
    label: "Celestial Script",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 80",
    nameplateClass: "np-celestial-script",
    preview: "Starfield glow with cosmic shimmer",
  },

  // Progress (Hour-gated)
  scholar_crest: {
    label: "Scholar's Crest",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "100 total hours",
    nameplateClass: "np-scholar-crest",
    preview: "Academic laurel border in deep green",
  },

  // Sprints
  inferno_tag: {
    label: "Inferno Tag",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "30 hrs/week",
    nameplateClass: "np-inferno-tag",
    preview: "Blazing fire gradient — for grinders only",
  },

  ////////////////////////// NEW ADDITIONS UNORGANIZED ////////////////////////////////

  // ── NEW FONTS ────────────────────────────────────────────────────
  raleway: {
    label: "Raleway",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 14",
    googleFont: "Raleway:wght@300;400;600",
    cssVars: { "--user-font": "'Raleway', 'Helvetica Neue', sans-serif" },
  },
  spectral: {
    label: "Spectral",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 22",
    googleFont: "Spectral:ital,wght@0,300;0,400;0,600;1,400",
    cssVars: { "--user-font": "'Spectral', Georgia, serif" },
  },
  josefin_slab: {
    label: "Josefin Slab",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "75 total hours",
    googleFont: "Josefin+Slab:wght@300;400;600",
    cssVars: { "--user-font": "'Josefin Slab', 'Times New Roman', serif" },
  },
  bebas_neue: {
    label: "Bebas Neue",
    category: "fonts",
    rewardType: "sprint",
    unlockHint: "15 hrs/week",
    googleFont: "Bebas+Neue",
    cssVars: { "--user-font": "'Bebas Neue', Impact, sans-serif" },
  },
  permanent_marker: {
    label: "Permanent Marker",
    category: "fonts",
    rewardType: "sprint",
    unlockHint: "20 hrs/month",
    googleFont: "Permanent+Marker",
    cssVars: { "--user-font": "'Permanent Marker', cursive" },
  },

  // ── NEW NAMEPLATES ────────────────────────────────────────────────
  silver_thread: {
    label: "Silver Thread",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 8",
    nameplateClass: "np-silver-thread",
    preview: "Brushed silver metallic with fine thread border",
  },
  midnight_ink: {
    label: "Midnight Ink",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 35",
    nameplateClass: "np-midnight-ink",
    preview: "Dark watercolor wash with ink-bleed edges",
  },
  crystalline: {
    label: "Crystalline",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 55",
    nameplateClass: "np-crystalline",
    preview: "Frosted glass with prismatic edge glints",
  },
  rose_gold_frame: {
    label: "Rose Gold",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "50 total hours",
    nameplateClass: "np-rose-gold",
    preview: "Warm rose gold gradient with satin sheen",
  },
  laurel_wreath: {
    label: "Laurel Wreath",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "250 total hours",
    nameplateClass: "np-laurel-wreath",
    preview: "Classical olive-green laurel with gold leaf accents",
  },
  storm_seal: {
    label: "Storm Seal",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "25 hrs/week",
    nameplateClass: "np-storm-seal",
    preview: "Dark storm clouds with electric blue flicker",
  },
}

export const CATEGORY_LABELS = {
  fonts: "Fonts",
  rings: "Rings",
  overlays: "Overlays",
  nameplates: "Nameplates",
}
