// wardrobeConfig.js
export const WARDROBE_CONFIG = {
  // ══════════════════════════════════════
  // FONTS
  // ══════════════════════════════════════

  // --- PROGRESS (Level-Gated) ---
  // ════════════════════════════════════════════════════════════════════════════
  // FONTS — sorted by unlock: Level → Hours → Weekly → Monthly
  // ════════════════════════════════════════════════════════════════════════════

  // ── LEVEL-GATED (L5 → L100) ──────────────────────────────────────────────

  // ─── FONTS — wardrobeConfig ───────────────────────────────────────────────────
  // Source of truth: UNLOCK_RULES (trigger + threshold)
  // rewardType: "progress" = level or totalMinutes gate
  //             "sprint"   = weeklyMinutes or monthlyMinutes gate
  // unlockHint: human-readable string matching the UNLOCK_RULES description exactly
  // ─────────────────────────────────────────────────────────────────────────────

  // ══════════════════════════════════════════════════════════════════════════════
  // LEVEL-GATED  (trigger: "level", sorted by threshold ascending)
  // ══════════════════════════════════════════════════════════════════════════════

  scholarly_serif: {
    label: "Scholarly Serif",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 5",
    googleFont: null,
    preview: "Classic academic serif. Clean, trustworthy.",
    cssVars: { "--user-font": "'Georgia', 'Times New Roman', serif" },
  },
  chewy: {
    label: "Chewy",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 6",
    googleFont: "Chewy",
    preview: "Bubbly rounded cartoon. Sugar-rush energy.",
    cssVars: { "--user-font": "'Chewy', cursive" },
  },
  jetbrains_mono: {
    label: "JetBrains Mono",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 7",
    googleFont: "JetBrains+Mono:wght@300;400;500",
    preview: "Built for code. Ligatures, precision, intent.",
    cssVars: { "--user-font": "'JetBrains Mono', monospace" },
  },
  boogaloo: {
    label: "Boogaloo",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 8",
    googleFont: "Boogaloo",
    preview: "Casual rounded retro. Friendly and bouncy.",
    cssVars: { "--user-font": "'Boogaloo', 'Impact', cursive" },
  },
  space_grotesk: {
    label: "Space Grotesk",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 9",
    googleFont: "Space+Grotesk:wght@300;400;500;600",
    preview: "Futuristic sans. Clean and slightly alien.",
    cssVars: { "--user-font": "'Space Grotesk', sans-serif" },
  },
  fredoka: {
    label: "Fredoka",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 10",
    googleFont: "Fredoka:wght@300..700",
    preview: "Rounded friendly display. Approachable energy.",
    cssVars: { "--user-font": "'Fredoka', sans-serif" },
  },
  raleway: {
    label: "Raleway",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 11",
    googleFont: "Raleway:wght@300;400;600",
    preview: "Elegant thin display. Art Deco bones.",
    cssVars: { "--user-font": "'Raleway', 'Helvetica Neue', sans-serif" },
  },
  luckiest_guy: {
    label: "Luckiest Guy",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 12",
    googleFont: "Luckiest+Guy",
    preview: "Chunky retro bold. Loud and proud.",
    cssVars: { "--user-font": "'Luckiest Guy', cursive" },
  },
  lora_serif: {
    label: "Lora",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 13",
    googleFont: "Lora:ital,wght@0,400;0,600;1,400",
    preview: "Contemporary serif. Warm, balanced, literary.",
    cssVars: { "--user-font": "'Lora', Georgia, serif" },
  },
  permanent_marker: {
    label: "Permanent Marker",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 14",
    googleFont: "Permanent+Marker",
    preview: "Sharpie-thick handwriting. Leaves a mark.",
    cssVars: { "--user-font": "'Permanent Marker', cursive" },
  },
  fondamento: {
    label: "Calligrapher",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 15",
    googleFont: "Fondamento:ital@0;1",
    preview: "Italic calligraphic script. Deliberate strokes.",
    cssVars: { "--user-font": "'Fondamento', cursive" },
  },
  modern_minimalist: {
    label: "Modern Minimalist",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 16",
    googleFont: null,
    preview: "Inter — clean, airy, distraction-free.",
    cssVars: { "--user-font": "'Inter', 'Helvetica Neue', sans-serif" },
  },
  spectral: {
    label: "Spectral",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 17",
    googleFont: "Spectral:ital,wght@0,300;0,400;0,600;1,400",
    preview: "Screen-optimized literary serif. Refined.",
    cssVars: { "--user-font": "'Spectral', Georgia, serif" },
  },
  rajdhani: {
    label: "Rajdhani",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 18",
    googleFont: "Rajdhani:wght@300;400;500;600;700",
    preview: "Condensed military-grade sans. Efficient.",
    cssVars: { "--user-font": "'Rajdhani', 'Arial Narrow', sans-serif" },
  },
  lilita_one: {
    label: "Lilita One",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 19",
    googleFont: "Lilita+One",
    preview: "Thick Latin bold display. Punchy headlines.",
    cssVars: { "--user-font": "'Lilita One', Impact, sans-serif" },
  },
  modak: {
    label: "Modak",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 20",
    googleFont: "Modak",
    preview: "Ultra-rounded chunky display. Soft and bold.",
    cssVars: { "--user-font": "'Modak', cursive" },
  },
  titan_one: {
    label: "Titan One",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 21",
    googleFont: "Titan+One",
    preview: "Hulking rounded display. Pure weight.",
    cssVars: { "--user-font": "'Titan One', Impact, cursive" },
  },
  cinzel: {
    label: "Cinzel",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 22",
    googleFont: "Cinzel:wght@400;600;700",
    preview: "Chiseled from Roman stone. Commanding, regal.",
    cssVars: { "--user-font": "'Cinzel', serif" },
  },
  megrim: {
    label: "Cyber Glitch",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 23",
    googleFont: "Megrim",
    preview: "Ultra-thin geometric. Barely holding together.",
    cssVars: { "--user-font": "'Megrim', cursive" },
  },
  exo_2: {
    label: "Exo 2",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 24",
    googleFont: "Exo+2:ital,wght@0,300;0,400;0,600;1,400",
    preview: "Geometric sci-fi sans. Variable and versatile.",
    cssVars: { "--user-font": "'Exo 2', 'Helvetica Neue', sans-serif" },
  },
  fascinate: {
    label: "Art Deco Flare",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 25",
    googleFont: "Fascinate",
    preview: "Art Deco display. Gatsby-era gravitas.",
    cssVars: { "--user-font": "'Fascinate', display" },
  },
  cormorant_garamond: {
    label: "Cormorant Garamond",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 26",
    googleFont: "Cormorant+Garamond:ital,wght@0,400;0,600;1,400",
    preview: "Dark academia elegance. Whispers of candlelight.",
    cssVars: { "--user-font": "'Cormorant Garamond', Georgia, serif" },
  },
  sigmar: {
    label: "Sigmar",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 27",
    googleFont: "Sigmar",
    preview: "Rounded mega-bold display. Cheerful muscle.",
    cssVars: { "--user-font": "'Sigmar', cursive" },
  },
  monoton: {
    label: "Monoton",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 28",
    googleFont: "Monoton",
    preview: "Neon double-line display. Retro glow.",
    cssVars: { "--user-font": "'Monoton', cursive" },
  },
  shrikhand: {
    label: "Shrikhand",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 29",
    googleFont: "Shrikhand",
    preview: "Gujarati-inspired bold display. Distinctive curves.",
    cssVars: { "--user-font": "'Shrikhand', Impact, cursive" },
  },
  stix_two: {
    label: "Scientific Elite",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 30",
    googleFont: "STIX+Two+Text:ital,wght@0,400..700;1,400..700",
    preview: "Journal-grade math serif. For those who write equations.",
    cssVars: { "--user-font": "'STIX Two Text', serif" },
  },
  knewave: {
    label: "Knewave",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 31",
    googleFont: "Knewave",
    preview: "Chunky marker pen. Written fast, felt hard.",
    cssVars: { "--user-font": "'Knewave', 'Impact', cursive" },
  },
  creepster: {
    label: "Creepster",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 32",
    googleFont: "Creepster",
    preview: "Dripping horror display. Spooky season permanent.",
    cssVars: { "--user-font": "'Creepster', cursive" },
  },
  abril_fatface: {
    label: "Abril Fatface",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 33",
    googleFont: "Abril+Fatface",
    preview: "Victorian poster serif. Dramatic contrast strokes.",
    cssVars: { "--user-font": "'Abril Fatface', 'Times New Roman', cursive" },
  },
  stick_no_bills: {
    label: "Stick No Bills",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 34",
    googleFont: "Stick+No+Bills:wght@200..800",
    preview: "Ultra-expanded condensed. Maximum presence.",
    cssVars: { "--user-font": "'Stick No Bills', 'Arial', sans-serif" },
  },
  tourney: {
    label: "Cyber Athlete",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 35",
    googleFont: "Tourney:wght@100..900",
    preview: "Esports-grade variable display. Championship energy.",
    cssVars: { "--user-font": "'Tourney', display" },
  },
  bungee_shade: {
    label: "Bungee Shade",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 36",
    googleFont: "Bungee+Shade",
    preview: "Inline shadow block letters. Retro dimensional.",
    cssVars: { "--user-font": "'Bungee Shade', cursive" },
  },
  dela_gothic_one: {
    label: "Dela Gothic One",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 37",
    googleFont: "Dela+Gothic+One",
    preview: "Japanese-influenced ultra-bold. Zero compromise.",
    cssVars: { "--user-font": "'Dela Gothic One', Impact, sans-serif" },
  },
  righteous: {
    label: "Righteous",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 38",
    googleFont: "Righteous",
    preview: "70s bold display. Confident and loud.",
    cssVars: { "--user-font": "'Righteous', Impact, cursive" },
  },
  reem_kufi_fun: {
    label: "Reem Kufi Fun",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 39",
    googleFont: "Reem+Kufi+Fun",
    preview: "Arabic-inspired rounded display. Geometric warmth.",
    cssVars: { "--user-font": "'Reem Kufi Fun', sans-serif" },
  },
  emblema_one: {
    label: "Emblema One",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 40",
    googleFont: "Emblema+One",
    preview: "Retro badge display. Old-school crest energy.",
    cssVars: { "--user-font": "'Emblema One', cursive" },
  },
  ranchers: {
    label: "Ranchers",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 41",
    googleFont: "Ranchers",
    preview: "Vintage western. Open range attitude.",
    cssVars: { "--user-font": "'Ranchers', cursive" },
  },
  fascinate_inline: {
    label: "Fascinate Inline",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 42",
    googleFont: "Fascinate+Inline",
    preview: "Inline Art Deco. Gatsby-era luxury.",
    cssVars: { "--user-font": "'Fascinate Inline', cursive" },
  },
  // Level 43–44: intentional gap — no entries
  foldit: {
    label: "Foldit",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 45",
    googleFont: "Foldit:wght@100..900",
    preview: "Origami-folded variable. Geometric and sculptural.",
    cssVars: { "--user-font": "'Foldit', cursive" },
  },
  orbitron: {
    label: "Orbitron",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 46",
    googleFont: "Orbitron:wght@400;600;700",
    preview: "Sci-fi geometric. From the year 2140.",
    cssVars: { "--user-font": "'Orbitron', sans-serif" },
  },
  pixelify_sans: {
    label: "Pixelify Sans",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 47",
    googleFont: "Pixelify+Sans:wght@400..700",
    preview: "Modern clean pixel. Readable retro-game aesthetic.",
    cssVars: { "--user-font": "'Pixelify Sans', monospace" },
  },
  shojumaru: {
    label: "Shojumaru",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 48",
    googleFont: "Shojumaru",
    preview: "Japanese brush-influenced display. Striking strokes.",
    cssVars: { "--user-font": "'Shojumaru', cursive" },
  },
  freckle_face: {
    label: "Freckle Face",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 49",
    googleFont: "Freckle+Face",
    preview: "Playful spotted display. Quirky and lovable.",
    cssVars: { "--user-font": "'Freckle Face', cursive" },
  },
  vt323: {
    label: "VT323",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 50",
    googleFont: "VT323",
    preview: "Terminal phosphor. Straight from the mainframe.",
    cssVars: { "--user-font": "'VT323', 'Courier New', monospace" },
  },
  wallpoet: {
    label: "Wallpoet",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 51",
    googleFont: "Wallpoet",
    preview: "Stencil street display. Urban grid precision.",
    cssVars: { "--user-font": "'Wallpoet', cursive" },
  },
  nosifer: {
    label: "Nosifer",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 52",
    googleFont: "Nosifer",
    preview: "Dripping horror sans. Undead authority.",
    cssVars: { "--user-font": "'Nosifer', cursive" },
  },
  moirai_one: {
    label: "Moirai One",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 53",
    googleFont: "Moirai+One",
    preview: "Korean-influenced gothic bold. Dramatic weight.",
    cssVars: { "--user-font": "'Moirai One', Impact, display" },
  },
  // Level 54: intentional gap — no entry
  bitcount_ink: {
    label: "Bitcount Ink",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 55",
    googleFont: "Bitcount+Ink",
    preview: "Pixel ink matrix. Digital calligraphy.",
    cssVars: { "--user-font": "'Bitcount Ink', monospace" },
  },
  syncopate: {
    label: "Syncopate",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 56",
    googleFont: "Syncopate:wght@400;700",
    preview: "Spaced-out all-caps display. Futuristic rhythm.",
    cssVars: { "--user-font": "'Syncopate', sans-serif" },
  },
  black_ops_one: {
    label: "Black Ops One",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 57",
    googleFont: "Black+Ops+One",
    preview: "Military stencil. Mission-critical letterforms.",
    cssVars: { "--user-font": "'Black Ops One', cursive" },
  },
  griffy: {
    label: "Griffy",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 58",
    googleFont: "Griffy",
    preview: "Hand-drawn grunge. Scrawled on a dungeon wall.",
    cssVars: { "--user-font": "'Griffy', cursive" },
  },
  teko: {
    label: "Teko",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 59",
    googleFont: "Teko:wght@300;400;500;600;700",
    preview: "Narrow HUD font. Scoreboard-ready efficiency.",
    cssVars: { "--user-font": "'Teko', 'Arial Narrow', sans-serif" },
  },
  rubik_glitch: {
    label: "Rubik Glitch",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 60",
    googleFont: "Rubik+Glitch",
    preview: "Corrupted data display. Signal interference aesthetic.",
    cssVars: { "--user-font": "'Rubik Glitch', sans-serif" },
  },
  // Levels 61–64: intentional gap — no entries
  bebas_neue: {
    label: "Bebas Neue",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 61",
    googleFont: "Bebas+Neue",
    preview: "All-caps condensed. Posters. Billboards. Power.",
    cssVars: { "--user-font": "'Bebas Neue', Impact, sans-serif" },
  },
  honk: {
    label: "Honk",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 65",
    googleFont: "Honk",
    preview: "COLRv1 circus display. Festive and impossible to ignore.",
    cssVars: { "--user-font": "'Honk', cursive" },
  },

  rubik_doodle_shadow: {
    label: "Doodle Shadow",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 67",
    googleFont: "Rubik+Doodle+Shadow",
    preview: "Hand-doodled shadow letters. Playful scribble energy.",
    cssVars: { "--user-font": "'Rubik Doodle Shadow', system-ui" },
  },

  rubik_spray_paint: {
    label: "Spray Paint",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 69",
    googleFont: "Rubik+Spray+Paint",
    preview: "Rough aerosol texture. Tagged on a concrete wall.",
    cssVars: { "--user-font": "'Rubik Spray Paint', display" },
  },

  rubik_dirt: {
    label: "Rubik Dirt",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 71",
    googleFont: "Rubik+Dirt",
    preview: "Mud-splattered raw texture. Earned in the grind.",
    cssVars: { "--user-font": "'Rubik Dirt', display" },
  },

  kablammo: {
    label: "Kablammo",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 73",
    googleFont: "Kablammo",
    preview: "Wobbly color cartoon. Letters that explode off the page.",
    cssVars: { "--user-font": "'Kablammo', system-ui" },
  },
  kalnia_glaze: {
    label: "Kalnia Glaze",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 75",
    googleFont: "Kalnia+Glaze",
    preview: "COLRv1 glazed serif. Prestige tier typography.",
    cssVars: { "--user-font": "'Kalnia Glaze', serif" },
  },
  unifraktur: {
    label: "Blackletter Elite",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 77",
    googleFont: "UnifrakturMaguntia",
    preview: "Medieval German blackletter. Ancient manuscript authority.",
    cssVars: { "--user-font": "'UnifrakturMaguntia', serif" },
  },
  sour_gummy: {
    label: "Sour Gummy",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 79",
    googleFont: "Sour+Gummy:wght@100..900",
    preview: "Candy-coated variable. Sweet, chunky, impossible to ignore.",
    cssVars: { "--user-font": "'Sour Gummy', cursive" },
  },
  rubik_puddles: {
    label: "Rubik Puddles",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 81",
    googleFont: "Rubik+Puddles",
    preview: "COLR watery blue. Letters submerged in liquid.",
    cssVars: { "--user-font": "'Rubik Puddles', display" },
  },
  rock_salt: {
    label: "Rock Salt",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 83",
    googleFont: "Rock+Salt",
    preview: "Gritty handwritten marker. Unfiltered expression.",
    cssVars: { "--user-font": "'Rock Salt', 'Comic Sans MS', cursive" },
  },
  // Levels 76–84: intentional gap — no entries
  sixtyfour_convergence: {
    label: "Sixtyfour Convergence",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "Level 85",
    googleFont: "Sixtyfour+Convergence",
    preview: "Variable pixel convergence. Earned by the few.",
    cssVars: { "--user-font": "'Sixtyfour Convergence', sans-serif" },
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // TOTAL HOURS  (trigger: "totalMinutes", sorted by threshold ascending)
  // ══════════════════════════════════════════════════════════════════════════════

  typewriter_pro: {
    label: "Typewriter Pro",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "50 total hours",
    googleFont: null,
    preview: "Courier monospace. Every keystroke deliberate.",
    cssVars: { "--user-font": "'Courier New', Courier, monospace" },
  },
  josefin_slab: {
    label: "Josefin Slab",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "75 total hours",
    googleFont: "Josefin+Slab:wght@300;400;600",
    preview: "Geometric slab with personality. Structured warmth.",
    cssVars: { "--user-font": "'Josefin Slab', 'Times New Roman', serif" },
  },
  climate_crisis: {
    label: "Brutalist",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "90 total hours",
    googleFont: "Climate+Crisis",
    preview: "Variable grotesque. Urgency rendered in letterform.",
    cssVars: { "--user-font": "'Climate Crisis', sans-serif" },
  },
  playfair_display: {
    label: "Playfair Display",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "100 total hours",
    googleFont: "Playfair+Display:ital,wght@0,400;0,700;1,400",
    preview: "High-contrast editorial serif. The classic refined persona.",
    cssVars: { "--user-font": "'Playfair Display', Georgia, serif" },
  },
  fira_code: {
    label: "Fira Code",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "150 total hours",
    googleFont: "Fira+Code:wght@300;400;500",
    preview: "Programming ligatures. Code that reads like poetry.",
    cssVars: { "--user-font": "'Fira Code', 'Courier New', monospace" },
  },
  major_mono: {
    label: "Abstract Mono",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "200 total hours",
    googleFont: "Major+Mono+Display",
    preview: "Geometric monospace display. Structured abstraction.",
    cssVars: { "--user-font": "'Major Mono Display', monospace" },
  },
  dm_serif: {
    label: "DM Serif Display",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "250 total hours",
    googleFont: "DM+Serif+Display:ital@0;1",
    preview: "Dramatic headline serif. Confident and literary.",
    cssVars: { "--user-font": "'DM Serif Display', Georgia, serif" },
  },
  instrument_serif: {
    label: "Instrument Serif",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "500 total hours",
    googleFont: "Instrument+Serif:ital@0;1",
    preview: "Quiet sophistication. A new classic for the dedicated scholar.",
    cssVars: { "--user-font": "'Instrument Serif', Georgia, serif" },
  },
  syne_tactical: {
    label: "Syne Tactical",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "750 total hours",
    googleFont: "Syne:wght@400;800",
    preview: "Grotesque variable with character. Idiosyncratic precision.",
    cssVars: { "--user-font": "'Syne', sans-serif" },
  },
  bungee_tint: {
    label: "Bungee Tint",
    category: "fonts",
    rewardType: "progress",
    unlockHint: "1000 total hours",
    googleFont: "Bungee+Tint",
    preview: "Two-tone inline block. Bold with a highlight.",
    cssVars: { "--user-font": "'Bungee Tint', cursive" },
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // WEEKLY SPRINTS  (trigger: "weeklyMinutes", sorted by threshold ascending)
  // ══════════════════════════════════════════════════════════════════════════════

  retro_pixel: {
    label: "Retro Pixel",
    category: "fonts",
    rewardType: "sprint",
    unlockHint: "35hrs/week",
    googleFont: "Press+Start+2P",
    preview: "8-bit game font. Old-school energy.",
    cssVars: { "--user-font": "'Press Start 2P', monospace" },
  },
  faster_one: {
    label: "Faster One",
    category: "fonts",
    rewardType: "sprint",
    unlockHint: "45hrs/week",
    googleFont: "Faster+One",
    preview: "Racing condensed italic. Speed visualized.",
    cssVars: { "--user-font": "'Faster One', Impact, cursive" },
  },
  nabla: {
    label: "Isometric Glow",
    category: "fonts",
    rewardType: "sprint",
    unlockHint: "55hrs/week",
    googleFont: "Nabla",
    preview: "COLR 3D isometric. Letters float in another dimension.",
    cssVars: { "--user-font": "'Nabla', system-ui" },
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // MONTHLY SPRINTS  (trigger: "monthlyMinutes", sorted by threshold ascending)
  // ══════════════════════════════════════════════════════════════════════════════

  bangers: {
    label: "Bangers",
    category: "fonts",
    rewardType: "marathon",
    unlockHint: "110hrs/month",
    googleFont: "Bangers",
    preview: "Comic book impact. POW — unapologetically loud.",
    cssVars: { "--user-font": "'Bangers', Impact, cursive" },
  },
  silkscreen: {
    label: "Silkscreen",
    category: "fonts",
    rewardType: "marathon",
    unlockHint: "170hrs/month",
    googleFont: "Silkscreen",
    preview: "Crisp pixel screen font. Sharp and legible.",
    cssVars: { "--user-font": "'Silkscreen', monospace" },
  },
  bungee_spice: {
    label: "Bungee Spice",
    category: "fonts",
    rewardType: "marathon",
    unlockHint: "230hrs/month",
    googleFont: "Bungee+Spice",
    preview: "COLR multicolor striped. Bold layered chromatic display.",
    cssVars: { "--user-font": "'Bungee Spice', cursive" },
  },

  // ══════════════════════════════════════
  // RINGS
  // ══════════════════════════════════════

  // TIER 1 RINGS (Levels 3-24)
  // slate_outline: {
  //   label: "Slate",
  //   category: "rings",
  //   rewardType: "progress",
  //   unlockHint: "Level 3",
  //   ringClass: "slate-outline-ring",
  // },

  medicine_ring: {
    label: "Medicine",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 5",
    ringClass: "medicine-prof-ring",
  },
  ring_bronze: {
    label: "Bronze",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 6",
    ringClass: "ring-2 ring-amber-700 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  law_ring: {
    label: "Law",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 7",
    ringClass: "law-prof-ring",
  },
  ring_silver: {
    label: "Silver",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 8",
    ringClass: "ring-2 ring-gray-400 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  engineering_ring: {
    label: "Engineering",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 9",
    ringClass: "engineering-prof-ring",
  },
  ring_gold: {
    label: "Gold",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 10",
    ringClass: "ring-2 ring-yellow-400 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  science_ring: {
    label: "Science",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 11",
    ringClass: "science-prof-ring",
  },
  ring_ruby: {
    label: "Ruby",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 12",
    ringClass: "ring-2 ring-red-500 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  arts_ring: {
    label: "Arts",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 13",
    ringClass: "arts-prof-ring",
  },
  ring_sapphire: {
    label: "Sapphire",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 14",
    ringClass: "ring-2 ring-blue-500 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  economics_ring: {
    label: "Economics",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 15",
    ringClass: "economics-prof-ring",
  },
  ring_emerald: {
    label: "Emerald",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 16",
    ringClass: "ring-2 ring-emerald-500 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  music_ring: {
    label: "Music",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 17",
    ringClass: "music-prof-ring",
  },
  ring_amethyst: {
    label: "Amethyst",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 18",
    ringClass: "ring-2 ring-purple-500 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  dentistry_ring: {
    label: "Dentistry",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 19",
    ringClass: "dentistry-prof-ring",
  },
  ring_obsidian: {
    label: "Obsidian",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 20",
    ringClass: "ring-2 ring-gray-900 ring-offset-2 ring-offset-base-100 rounded-full",
  },

  sports_ring: {
    label: "Sports",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 21",
    ringClass: "sports-prof-ring",
  },
  ring_ivory: {
    label: "Ivory",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 22",
    ringClass: "ring-2 ring-stone-200 ring-offset-2 ring-offset-base-100 rounded-full",
  },
  psychology_ring: {
    label: "Psychology",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 23",
    ringClass: "psychology-prof-ring",
  },
  ring_rose: {
    label: "Rose",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 24",
    ringClass: "ring-2 ring-pink-500 ring-offset-2 ring-offset-base-100 rounded-full",
  },

  veterinary_ring: {
    label: "Veterinary",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 25",
    ringClass: "veterinary-prof-ring",
  },

  // TIER 2 RINGS (Levels 27-50)

  leviathan: {
    label: "Leviathan",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 27",
    ringClass: "leviathan-ring",
  },
  neon_halo_ring: {
    label: "Neon Halo",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 28",
    ringClass: "neon-halo-ring",
  },
  glacier: {
    label: "Glacier",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 29",
    ringClass: "glacier-ring",
  },
  jade_glow: {
    label: "Jade Glow",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 30",
    ringClass: "jade-glow-ring",
  },
  bioluminescence: {
    label: "Bioluminescence",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 31",
    ringClass: "bioluminescence-ring",
  },
  frozen_crystal: {
    label: "Frozen Crystal",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 32",
    ringClass: "frozen-crystal-ring",
  },
  holographic_foil: {
    label: "Holographic Foil",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 33",
    ringClass: "holographic-foil-ring",
  },
  rose_quartz: {
    label: "Rose Quartz",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 34",
    ringClass: "rose-quartz-ring",
  },
  sapphire_lattice: {
    label: "Sapphire Lattice",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 35",
    ringClass: "sapphire-lattice-ring",
  },
  scholars_glow: {
    label: "Scholar's Glow",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 36",
    ringClass: "scholars-glow-ring",
  },
  gravity_wave: {
    label: "Gravity Wave",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 37",
    ringClass: "gravity-wave-ring",
  },
  copper_coil: {
    label: "Copper Coil",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 38",
    ringClass: "copper-coil-ring",
  },
  amber_fossil: {
    label: "Amber Fossil",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 39",
    ringClass: "amber-fossil-ring",
  },
  lavender_drift: {
    label: "Lavender Drift",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 40",
    ringClass: "lavender-drift-ring",
  },
  bismuth_crystal: {
    label: "Bismuth Crystal",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 41",
    ringClass: "bismuth-crystal-ring",
  },
  blood_moon: {
    label: "Blood Moon",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 42",
    ringClass: "blood-moon-ring",
  },
  absinthe: {
    label: "Absinthe",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 43",
    ringClass: "absinthe-ring",
  },
  twilight_band: {
    label: "Twilight Band",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 44",
    ringClass: "twilight-band-ring",
  },
  petal_storm: {
    label: "Petal Storm",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 45",
    ringClass: "petal-storm-ring",
  },
  ivy_league: {
    label: "Ivy League",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 46",
    ringClass: "ivy-league-ring",
  },
  chromatic_aberration: {
    label: "Chromatic Aberration",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 47",
    ringClass: "chromatic-aberration-ring",
  },
  spectral_shift: {
    label: "Spectral Shift",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 48",
    ringClass: "spectral-shift-ring",
  },

  midnight_sovereign: {
    label: "Midnight Sovereign",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 49",
    ringClass: "midnight-sovereign-ring",
  },
  thunder_strike: {
    label: "Thunder Strike",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 50",
    ringClass: "thunder-strike-ring",
  },
  malachite: {
    label: "Malachite",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 51",
    ringClass: "malachite-ring",
  },
  radium_dial: {
    label: "Radium Dial",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 53",
    ringClass: "radium-dial-ring",
  },

  // TIER 3 RINGS (Levels 55-63)
  prism_spin: {
    label: "Prism",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 55",
    ringClass: "prism-spin-ring",
  },
  neurotoxin: {
    label: "Neurotoxin",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 56",
    ringClass: "neurotoxin-ring",
  },
  seafoam_wave: {
    label: "Seafoam Wave",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 57",
    ringClass: "seafoam-wave-ring",
  },
  mirage: {
    label: "Mirage",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 58",
    ringClass: "mirage-ring",
  },
  diamond_edge: {
    label: "Diamond Edge",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 59",
    ringClass: "diamond-edge-ring",
  },
  wildfire: {
    label: "Wildfire",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 60",
    ringClass: "wildfire-ring",
  },
  void_static: {
    label: "Void Static",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 61",
    ringClass: "void-static-ring",
  },
  voltage: {
    label: "Voltage",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 62",
    ringClass: "voltage-ring",
  },
  cosmic_dust: {
    label: "Cosmic Dust",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 63",
    ringClass: "cosmic-dust-ring",
  },
  burning_ice: {
    label: "Burning Ice",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 64",
    ringClass: "burning-ice-ring",
  },

  // TIER 4 RINGS (Levels 65-75)
  zen_blossom: {
    label: "Zen Blossom",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 65",
    ringClass: "zen-blossom-ring",
  },
  opal: {
    label: "Opal",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 66",
    ringClass: "opal-ring",
  },
  abyssal: {
    label: "Abyssal",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 67",
    ringClass: "abyssal-ring",
  },
  necromancer: {
    label: "Necromancer",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 68",
    ringClass: "necromancer-ring",
  },
  eternal_flame: {
    label: "Eternal Flame",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 69",
    ringClass: "eternal-flame-ring",
  },
  thunderhead: {
    label: "Thunderhead",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 70",
    ringClass: "thunderhead-ring",
  },
  celestial_orbit: {
    label: "Celestial Orbit",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 71",
    ringClass: "celestial-orbit-ring",
  },
  obsidian_fracture: {
    label: "Obsidian Fracture",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 72",
    ringClass: "obsidian-fracture-ring",
  },
  phantom_drift: {
    label: "Phantom Drift",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 73",
    ringClass: "phantom-drift-ring",
  },
  chrono: {
    label: "Chrono",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 74",
    ringClass: "chrono-ring",
  },
  void_smoke: {
    label: "Void Smoke",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 75",
    ringClass: "void-smoke-ring",
  },

  sunstone: {
    label: "Sunstone",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 76",
    ringClass: "sunstone-ring",
  },

  // TIER 5 RINGS (Levels 77-83)
  magma_flow: {
    label: "Magma Flow",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 77",
    ringClass: "magma-flow-ring",
  },
  phosphor: {
    label: "Phosphor",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 78",
    ringClass: "phosphor-ring",
  },
  cyber_neon_pulse: {
    label: "Cyber Neon Pulse",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 79",
    ringClass: "cyber-neon-pulse-ring",
  },
  glitch_art: {
    label: "Glitch Art",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 80",
    ringClass: "glitch-art-ring",
  },
  quantum_flux: {
    label: "Quantum Flux",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 81",
    ringClass: "quantum-flux-ring",
  },
  neon_flamingo: {
    label: "Neon Flamingo",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 82",
    ringClass: "neon-flamingo-ring",
  },
  crimson_tide: {
    label: "Crimson Tide",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 83",
    ringClass: "crimson-tide-ring",
  },
  astral_crown: {
    label: "Astral Crown",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 84",
    ringClass: "astral-crown-ring",
  },
  digital_fracture: {
    label: "Digital Fracture",
    category: "rings",
    rewardType: "progress",
    unlockHint: "Level 85",
    ringClass: "digital-fracture-ring",
  },

  // TOTAL HOUR RINGS
  sakura_ring: {
    label: "Sakura",
    category: "rings",
    rewardType: "progress",
    unlockHint: "250 total hours",
    ringClass: "sakura-ring",
  },
  moonbeam: {
    label: "Moonbeam",
    category: "rings",
    rewardType: "progress",
    unlockHint: "350 total hours",
    ringClass: "moonbeam-ring",
  },
  amber_sunset: {
    label: "Amber Sunset",
    category: "rings",
    rewardType: "progress",
    unlockHint: "500 total hours",
    ringClass: "amber-sunset-ring",
  },
  deep_ocean_ring: {
    label: "Deep Ocean",
    category: "rings",
    rewardType: "progress",
    unlockHint: "600 total hours",
    ringClass: "deep-ocean-ring",
  },
  aurora_borealis: {
    label: "Aurora Borealis",
    category: "rings",
    rewardType: "progress",
    unlockHint: "750 total hours",
    ringClass: "aurora-borealis-ring",
  },
  starfield_ring: {
    label: "Starfield",
    category: "rings",
    rewardType: "progress",
    unlockHint: "850 total hours",
    ringClass: "starfield-ring",
  },
  singularity_ring: {
    label: "Singularity",
    category: "rings",
    rewardType: "progress",
    unlockHint: "1000 total hours",
    ringClass: "singularity-ring",
  },
  solar_flare: {
    label: "Solar Flare",
    category: "rings",
    rewardType: "progress",
    unlockHint: "1500 total hours",
    ringClass: "solar-flare-ring",
  },

  // WEEKLY SPRINTS
  grindstone_ring: {
    label: "Grindstone",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "30 hrs/week",
    ringClass: "grindstone-ring",
  },
  overdrive_ring: {
    label: "Overdrive",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "40 hrs/week",
    ringClass: "overdrive-ring",
  },
  neon_circuit: {
    label: "Neon Circuit",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "60 hrs/week",
    ringClass: "neon-circuit-ring",
  },
  electric_pulse: {
    label: "Electric Pulse",
    category: "rings",
    rewardType: "sprint",
    unlockHint: "70 hrs/week",
    ringClass: "electric-pulse-ring",
  },

  // MONTHLY SPRINTS
  persistence_ring: {
    label: "Persistence",
    category: "rings",
    rewardType: "marathon",
    unlockHint: "120 hrs/month",
    ringClass: "persistence-ring",
  },
  marathon_ring: {
    label: "Marathon",
    category: "rings",
    rewardType: "marathon",
    unlockHint: "180 hrs/month",
    ringClass: "marathon-ring",
  },
  titan_ring: {
    label: "Titan",
    category: "rings",
    rewardType: "marathon",
    unlockHint: "240 hrs/month",
    ringClass: "titan-ring",
  },

  // ══════════════════════════════════════
  // OVERLAYS
  // ══════════════════════════════════════

  // Progress (Level-gated)
  snowfall: {
    label: "Snowfall",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 15",
    overlayClass: "snowfall-overlay",
  },
  fireflies: {
    label: "Fireflies",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 22",
    overlayClass: "fireflies-overlay",
  },
  northern_lights: {
    label: "Northern Lights",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 45",
    overlayClass: "northern-lights-overlay",
  },
  star_rain: {
    label: "Star Rain",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "Level 70",
    overlayClass: "star-rain-overlay",
  },

  // Progress (Hour-gated)
  dust_particles: {
    label: "Dust Particles",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "50 total hours",
    overlayClass: "dust-particles-overlay",
  },
  nebula_mist: {
    label: "Nebula Mist",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "100 total hours",
    overlayClass: "nebula-mist-overlay",
  },
  rainy_window: {
    label: "Rainy Window",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "150 total hours",
    overlayClass: "rainy-window-overlay",
  },
  falling_leaves: {
    label: "Falling Leaves",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "200 total hours",
    overlayClass: "falling-leaves-overlay",
  },
  sakura_breeze: {
    label: "Sakura Breeze",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "300 total hours",
    overlayClass: "sakura-breeze-overlay",
  },
  fog_drift: {
    label: "Fog Drift",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "400 total hours",
    overlayClass: "fog-drift-overlay",
  },
  confetti_burst: {
    label: "Confetti Burst",
    category: "overlays",
    rewardType: "progress",
    unlockHint: "1000 total hours",
    overlayClass: "confetti-burst-overlay",
  },

  // Sprints
  matrix_code: {
    label: "Matrix Code",
    category: "overlays",
    rewardType: "sprint",
    unlockHint: "20 hrs/week",
    overlayClass: "matrix-code-overlay",
  },
  ember_storm: {
    label: "Ember Storm",
    category: "overlays",
    rewardType: "sprint",
    unlockHint: "30 hrs/week",
    overlayClass: "ember-storm-overlay",
  },
  crystal_frost: {
    label: "Crystal Frost",
    category: "overlays",
    rewardType: "marathon",
    unlockHint: "80 hrs/month",
    overlayClass: "crystal-frost-overlay",
  },

  // ══════════════════════════════════════
  // NAMEPLATES
  // ══════════════════════════════════════

  // Level-gated
  lunar_moth: {
    label: "Lunar Moth",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 1",
    nameplateClass: "np-lunar-moth",
    preview: "Silvery wing eyespot halos — pale phosphorescence",
  },
  forest_shadow: {
    label: "Forest Shadow",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 2",
    nameplateClass: "np-vibrant-base np-vibrant-darkgreen",
    preview: "Deep hunter green with a subtle, dark emerald glint",
  },
  void_hex: {
    label: "Void Hex",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 3",
    nameplateClass: "np-void-hex",
    preview: "Near-black with indigo hex grid pattern right",
  },
  royal_violet: {
    label: "Royal Violet",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 4",
    nameplateClass: "np-vibrant-base np-vibrant-violet",
    preview: "Regal deep purple with a shimmering amethyst highlight",
  },
  obsidian_crown: {
    label: "Obsidian Crown",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 5",
    nameplateClass: "np-obsidian-crown",
    preview: "Pure black with crystalline glint sweeping right",
  },
  ancient_bronze: {
    label: "Ancient Bronze",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 6",
    nameplateClass: "np-vibrant-base np-vibrant-bronze",
    preview: "Weathered metallic copper with a warm amber reflection",
  },
  diamond_rain: {
    label: "Diamond Rain",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 7",
    nameplateClass: "np-diamond-rain",
    preview: "White sparkle particles cascade down the right",
  },
  quick_silver: {
    label: "Quick Silver",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 8",
    nameplateClass: "np-vibrant-base np-vibrant-silver",
    preview: "Flowing liquid mercury sheen sweeping across",
  },
  neon_kanji: {
    label: "Neon Kanji",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 9",
    nameplateClass: "np-neon-kanji",
    preview: "Deep crimson with glowing grid marks on right",
  },
  liquid_gold: {
    label: "Liquid Gold",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 10",
    nameplateClass: "np-vibrant-base np-vibrant-gold",
    preview: "Heavy molten gold with a sharp metallic reflection",
  },
  sakura_veil: {
    label: "Sakura Veil",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 11",
    nameplateClass: "np-sakura-veil",
    preview: "Soft pink petals drift across the right side",
  },
  electric_cobalt: {
    label: "Electric Cobalt",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 12",
    nameplateClass: "np-vibrant-base np-vibrant-blue",
    preview: "High-voltage blue with a bright cyan electric shine",
  },
  rust_faction: {
    label: "Rust Faction",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 13",
    nameplateClass: "np-rust-faction",
    preview: "Industrial amber with scratch-mark texture on right",
  },
  emerald_essence: {
    label: "Emerald Essence",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 14",
    nameplateClass: "np-vibrant-base np-vibrant-green",
    preview: "Lush forest green with a brilliant jade light sweep",
  },
  ocean_drift: {
    label: "Ocean Drift",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 15",
    nameplateClass: "np-ocean-drift",
    preview: "Teal diagonal wave lines sweep rightward",
  },
  crimson_fury: {
    label: "Crimson Fury",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 16",
    nameplateClass: "np-vibrant-base np-vibrant-red",
    preview: "Deep intense red with a moving blood-light highlight",
  },
  toxic_sludge: {
    label: "Toxic Sludge",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 17",
    nameplateClass: "np-toxic-sludge",
    preview: "Neon green bubbles float up on the right side",
  },
  neon_lotus: {
    label: "Neon Lotus",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 18",
    nameplateClass: "np-vibrant-base np-vibrant-pink",
    preview: "Vibrant hot pink with a soft magenta glow sweep",
  },
  obsidian_mirror: {
    label: "Obsidian Mirror",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 19",
    nameplateClass: "np-obsidian-mirror",
    preview: "Pure black with mercury liquid ripple interference",
  },
  glacial_cyan: {
    label: "Glacial Cyan",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 20",
    nameplateClass: "np-vibrant-base np-vibrant-cyan",
    preview: "Deep arctic blue with a sharp, icy crystal shine",
  },
  lava_core: {
    label: "Lava Core",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 21",
    nameplateClass: "np-lava-core",
    preview: "Deep orange molten blobs breathing on right",
  },
  midnight_void: {
    label: "Midnight Void",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 22",
    nameplateClass: "np-vibrant-base np-vibrant-midnight",
    preview: "Near-black ink with a subtle, haunting indigo shimmer",
  },
  cosmic_string: {
    label: "Cosmic String",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 23",
    nameplateClass: "np-cosmic-string",
    preview: "Vibrating string theory filaments in dark space",
  },
  electric_canary: {
    label: "Electric Canary",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 24",
    nameplateClass: "np-vibrant-base np-vibrant-yellow",
    preview: "High-voltage yellow with a blinding white light streak",
  },
  desert_storm: {
    label: "Desert Storm",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 25",
    nameplateClass: "np-desert-storm",
    preview: "Sandy amber dust cloud with dune gradient",
  },
  deep_atlantic: {
    label: "Deep Atlantic",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 26",
    nameplateClass: "np-vibrant-base np-vibrant-navy",
    preview: "Heavy midnight blue with a slow, ocean-depth shimmer",
  },
  amber_resin: {
    label: "Amber Resin",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 27",
    nameplateClass: "np-amber-resin",
    preview: "Honey amber with trapped suspended bubble orbs",
  },
  soft_velvet: {
    label: "Soft Velvet",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 28",
    nameplateClass: "np-vibrant-base np-vibrant-peach",
    preview: "Smooth peach-orange with a soft, creamy light sweep",
  },
  bioluminescent: {
    label: "Bioluminescent",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 29",
    nameplateClass: "np-bioluminescent",
    preview: "Deep-sea dark with teal/blue organic glow orbs",
  },
  bio_hazard: {
    label: "Bio Hazard",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 30",
    nameplateClass: "np-vibrant-base np-vibrant-lime",
    preview: "Radioactive lime green with an energetic fast-moving pulse",
  },
  phantom_tide: {
    label: "Phantom Tide",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 31",
    nameplateClass: "np-phantom-tide",
    preview: "Translucent grey-white waves phasing in and out",
  },
  velvet_noir: {
    label: "Velvet Noir",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 32",
    nameplateClass: "np-velvet-noir",
    preview: "Deep plum velvet with slow iridescent sheen sweep",
  },
  abyssal_rift: {
    label: "Abyssal Rift",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 33",
    nameplateClass: "np-abyssal-rift",
    preview: "Bioluminescent shadows in deep trench — pressure pulses",
  },
  arctic_circuit: {
    label: "Arctic Circuit",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 34",
    nameplateClass: "np-arctic-circuit",
    preview: "Ice blue with circuit grid trace marching right",
  },
  frost_weave: {
    label: "Frost Weave",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 35",
    nameplateClass: "np-frost-weave",
    preview: "Ice crystal lattice with blue-white shimmer",
  },
  phantom_garden: {
    label: "Phantom Garden",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 36",
    nameplateClass: "np-phantom-garden",
    preview: "Deep violet with glowing bloom orbs breathing on right",
  },
  northern_pine: {
    label: "Northern Pine",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 37",
    nameplateClass: "np-northern-pine",
    preview: "Starfield above, deep forest green below",
  },
  quantum_entanglement: {
    label: "Quantum Entanglement",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 38",
    nameplateClass: "np-quantum-entanglement",
    preview: "Dueling interference patterns — probability waves collapsing",
  },
  sundown_protocol: {
    label: "Sundown Protocol",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 39",
    nameplateClass: "np-sundown-protocol",
    preview: "Orange-to-violet sunset gradient sweeping right",
  },
  crystal_cave: {
    label: "Crystal Cave",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 40",
    nameplateClass: "np-crystal-cave",
    preview: "Geometric blue/white crystal facets refracting light",
  },
  rose_ash: {
    label: "Rose Ash",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 41",
    nameplateClass: "np-rose-ash",
    preview: "Faded vintage rose — desaturated petal glows",
  },
  phoenix_pyre: {
    label: "Phoenix Pyre",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 43",
    nameplateClass: "np-phoenix-pyre",
    preview: "Ash and golden embers rising from a rebirth flame",
  },
  ember_forge: {
    label: "Ember Forge",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 46",
    nameplateClass: "np-ember-forge",
    preview: "Dark metal with heat shimmer and ember glow right",
  },
  divine_fracture: {
    label: "Divine Fracture",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 48",
    nameplateClass: "np-divine-fracture",
    preview: "Sacred gold lattice tears open — divine radiance erupts",
  },
  koi_pond: {
    label: "Koi Pond",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 50",
    nameplateClass: "np-koi-pond",
    preview: "Water ripple rings, warm amber-orange koi glow",
  },
  hyperspace: {
    label: "Hyperspace",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 52",
    nameplateClass: "np-hyperspace",
    preview: "Star-streak warp speed light trails converging",
  },
  midnight_prism: {
    label: "Midnight Prism",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 53",
    nameplateClass: "np-midnight-prism",
    preview: "Black base with rainbow diffraction edge on right",
  },
  vaporwave: {
    label: "Vaporwave",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 54",
    nameplateClass: "np-vaporwave",
    preview: "Pink/purple retrowave grid scrolling on the right",
  },
  jade_matrix: {
    label: "Jade Matrix",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 55",
    nameplateClass: "np-jade-matrix",
    preview: "Green Matrix code rain falling in columns",
  },
  plasma_vent: {
    label: "Plasma Vent",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 56",
    nameplateClass: "np-plasma-vent",
    preview: "Teal/magenta plasma discharge crackling on right",
  },
  sage_mist: {
    label: "Sage Mist",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 57",
    nameplateClass: "np-sage-mist",
    preview: "Soft sage green fog layers drifting rightward",
  },
  celestial_collapse: {
    label: "Celestial Collapse",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 58",
    nameplateClass: "np-celestial-collapse",
    preview: "Supernova condensation into a neutron star core",
  },
  aurora_silk: {
    label: "Aurora Silk",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 61",
    nameplateClass: "np-aurora-silk",
    preview: "Full-width silky aurora: green to teal to violet",
  },
  void_collapse: {
    label: "Void Collapse",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 63",
    nameplateClass: "np-void-collapse",
    preview: "Spacetime pinches into a dark singularity",
  },
  neon_outrun: {
    label: "Neon Outrun",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 66",
    nameplateClass: "np-neon-outrun",
    preview: "Hot pink/cyan retrowave with scan lines scrolling right",
  },
  solar_coronation: {
    label: "Solar Coronation",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 68",
    nameplateClass: "np-solar-coronation",
    preview: "Violent solar flares and plasma arcs erupting",
  },
  crimson_lattice: {
    label: "Crimson Lattice",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 71",
    nameplateClass: "np-crimson-lattice",
    preview: "Dark red woven lattice with breathing glow",
  },
  glacial_obliteration: {
    label: "Glacial Obliteration",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 73",
    nameplateClass: "np-glacial-obliteration",
    preview: "Icy blue shards calving — sub-zero frost energy",
  },
  gold_leaf: {
    label: "Gold Leaf",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 76",
    nameplateClass: "np-gold-leaf",
    preview: "Layered gold foil with slow-shifting burnished glint",
  },
  temporal_fracture: {
    label: "Temporal Fracture",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 78",
    nameplateClass: "np-temporal-fracture",
    preview: "Clockwork geometry dissolving into light trails",
  },
  solar_loop: {
    label: "Solar Loop",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 81",
    nameplateClass: "np-solar-loop",
    preview: "Orange plasma arcs looping from right edge",
  },
  infernal_gate: {
    label: "Infernal Gate",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "Level 83",
    nameplateClass: "np-infernal-gate",
    preview: "Demonic geometric seals burning with sulfur and lava",
  },
  // ── TOTAL HOUR MILESTONES ─────────────────────────────────────────────────
  deep_void: {
    label: "Deep Void",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "100 total hours",
    nameplateClass: "np-deep-void",
    preview: "Dark indigo with twinkling star clusters on the right",
  },
  glitch_manifest: {
    label: "Glitch Manifest",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "200 total hours",
    nameplateClass: "np-glitch-manifest",
    preview: "Cyan scan lines jitter and glitch across the right",
  },
  copper_verdigris: {
    label: "Copper Verdigris",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "300 total hours",
    nameplateClass: "np-copper-verdigris",
    preview: "Aged copper/green patina crosshatch on right",
  },
  thunder_roll: {
    label: "Thunder Roll",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "400 total hours",
    nameplateClass: "np-thunder-roll",
    preview: "Dark indigo with lightning flash bursts on right",
  },
  // Note: key changed to lunar_moth_total or handled by logic if duplicate
  event_horizon: {
    label: "Event Horizon",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "600 total hours",
    nameplateClass: "np-event-horizon",
    preview: "Space-time tears diagonally bleeds pure light",
  },
  coral_tide: {
    label: "Coral Tide",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "700 total hours",
    nameplateClass: "np-coral-tide",
    preview: "Warm coral-salmon gradient with pulse rings",
  },
  plasma_throne: {
    label: "Plasma Throne",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "800 total hours",
    nameplateClass: "np-plasma-throne",
    preview: "Fusion filaments contained by magnetic lines",
  },
  frozen_tundra: {
    label: "Frozen Tundra",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "900 total hours",
    nameplateClass: "np-frozen-tundra",
    preview: "Pale blue-white with snowflake particle fall",
  },
  maelstrom: {
    label: "Maelstrom",
    category: "nameplates",
    rewardType: "progress",
    unlockHint: "1,000 total hours",
    nameplateClass: "np-maelstrom",
    preview: "Violent rotating storm bands with an amber eye",
  },

  // ── WEEKLY SPRINTS ────────────────────────────────────────────────────────
  copper_storm: {
    label: "Copper Storm",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "20 hrs/week",
    nameplateClass: "np-copper-storm",
    preview: "Copper wiring sparks with dark-grey static background",
  },
  solar_wind: {
    label: "Solar Wind",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "33 hrs/week",
    nameplateClass: "np-solar-wind",
    preview: "Yellow-white energy particles streaming rightward",
  },
  holographic: {
    label: "Holographic",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "38 hrs/week",
    nameplateClass: "np-holographic",
    preview: "Rainbow light sweep cycling across the right side",
  },
  eclipse_core: {
    label: "Eclipse Core",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "43 hrs/week",
    nameplateClass: "np-eclipse-core",
    preview: "Dark card with solar corona erupting from right edge",
  },
  neon_drip: {
    label: "Neon Drip",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "50 hrs/week",
    nameplateClass: "np-neon-drip",
    preview: "Multicolor neon paint dripping down the right side",
  },
  nuclear_bloom: {
    label: "Nuclear Bloom",
    category: "nameplates",
    rewardType: "sprint",
    unlockHint: "65 hrs/week",
    nameplateClass: "np-nuclear-bloom",
    preview: "Radioactive pulse rings expanding energy",
  },

  // ── MONTHLY SPRINTS ───────────────────────────────────────────────────────
  tempest_eye: {
    label: "Tempest Eye",
    category: "nameplates",
    rewardType: "marathon",
    unlockHint: "115 hrs/month",
    nameplateClass: "np-tempest-eye",
    preview: "Swirling storm bands with calm amber eye",
  },
  twilight_spire: {
    label: "Twilight Spire",
    category: "nameplates",
    rewardType: "marathon",
    unlockHint: "125 hrs/month",
    nameplateClass: "np-twilight-spire",
    preview: "Orange-to-indigo dusk with rising light beam",
  },
  midnight_oil: {
    label: "Midnight Oil",
    category: "nameplates",
    rewardType: "marathon",
    unlockHint: "175 hrs/month",
    nameplateClass: "np-midnight-oil",
    preview: "Deep navy with warm amber lamp glow on the right",
  },
  bloodmoon: {
    label: "Bloodmoon",
    category: "nameplates",
    rewardType: "marathon",
    unlockHint: "185 hrs/month",
    nameplateClass: "np-bloodmoon",
    preview: "Deep crimson eclipse with orbital arc rings",
  },
  ember_drift: {
    label: "Ember Drift",
    category: "nameplates",
    rewardType: "marathon",
    unlockHint: "190 hrs/month",
    nameplateClass: "np-ember-drift",
    preview: "Floating ember sparks rising from the bottom right",
  },
  singularity: {
    label: "Singularity",
    category: "nameplates",
    rewardType: "marathon",
    unlockHint: "235 hrs/month",
    nameplateClass: "np-singularity",
    preview: "Black hole accretion disk ablaze with jets",
  },
}

export const CATEGORY_LABELS = {
  fonts: "Fonts",
  rings: "Rings",
  overlays: "Overlays",
  nameplates: "Nameplates",
}
