// lib/utils/checkUnlocks.js
const UNLOCK_RULES = [
  // ════════════════════════════════════════
  // FONTS — Progress Rewards
  // ════════════════════════════════════════
  // ── LEVEL-GATED (one per level, 5–85) ────────────────────────────────────────
  {
    id: "scholarly_serif",
    category: "fonts",
    trigger: "level",
    threshold: 5,
    items: ["scholarly_serif"],
    description: "Reach Level 5",
  },
  {
    id: "chewy",
    category: "fonts",
    trigger: "level",
    threshold: 6,
    items: ["chewy"],
    description: "Reach Level 6",
  },
  {
    id: "jetbrains_mono",
    category: "fonts",
    trigger: "level",
    threshold: 7,
    items: ["jetbrains_mono"],
    description: "Reach Level 7",
  },
  {
    id: "boogaloo",
    category: "fonts",
    trigger: "level",
    threshold: 8,
    items: ["boogaloo"],
    description: "Reach Level 8",
  },
  {
    id: "space_grotesk",
    category: "fonts",
    trigger: "level",
    threshold: 9,
    items: ["space_grotesk"],
    description: "Reach Level 9",
  },
  {
    id: "fredoka",
    category: "fonts",
    trigger: "level",
    threshold: 10,
    items: ["fredoka"],
    description: "Reach Level 10",
  },
  {
    id: "raleway",
    category: "fonts",
    trigger: "level",
    threshold: 11,
    items: ["raleway"],
    description: "Reach Level 11",
  },
  {
    id: "luckiest_guy",
    category: "fonts",
    trigger: "level",
    threshold: 12,
    items: ["luckiest_guy"],
    description: "Reach Level 12",
  },
  {
    id: "lora_serif",
    category: "fonts",
    trigger: "level",
    threshold: 13,
    items: ["lora_serif"],
    description: "Reach Level 13",
  },
  {
    id: "permanent_marker",
    category: "fonts",
    trigger: "level",
    threshold: 14,
    items: ["permanent_marker"],
    description: "Reach Level 14",
  },
  {
    id: "fondamento",
    category: "fonts",
    trigger: "level",
    threshold: 15,
    items: ["fondamento"],
    description: "Reach Level 15",
  },
  {
    id: "modern_minimalist",
    category: "fonts",
    trigger: "level",
    threshold: 16,
    items: ["modern_minimalist"],
    description: "Reach Level 16",
  },
  {
    id: "spectral",
    category: "fonts",
    trigger: "level",
    threshold: 17,
    items: ["spectral"],
    description: "Reach Level 17",
  },
  {
    id: "rajdhani",
    category: "fonts",
    trigger: "level",
    threshold: 18,
    items: ["rajdhani"],
    description: "Reach Level 18",
  },
  {
    id: "lilita_one",
    category: "fonts",
    trigger: "level",
    threshold: 19,
    items: ["lilita_one"],
    description: "Reach Level 19",
  },
  {
    id: "modak",
    category: "fonts",
    trigger: "level",
    threshold: 20,
    items: ["modak"],
    description: "Reach Level 20",
  },
  {
    id: "titan_one",
    category: "fonts",
    trigger: "level",
    threshold: 21,
    items: ["titan_one"],
    description: "Reach Level 21",
  },
  {
    id: "cinzel",
    category: "fonts",
    trigger: "level",
    threshold: 22,
    items: ["cinzel"],
    description: "Reach Level 22",
  },
  {
    id: "megrim",
    category: "fonts",
    trigger: "level",
    threshold: 23,
    items: ["megrim"],
    description: "Reach Level 23",
  },
  {
    id: "exo_2",
    category: "fonts",
    trigger: "level",
    threshold: 24,
    items: ["exo_2"],
    description: "Reach Level 24",
  },
  {
    id: "fascinate",
    category: "fonts",
    trigger: "level",
    threshold: 25,
    items: ["fascinate"],
    description: "Reach Level 25",
  },
  {
    id: "cormorant_garamond",
    category: "fonts",
    trigger: "level",
    threshold: 26,
    items: ["cormorant_garamond"],
    description: "Reach Level 26",
  },
  {
    id: "sigmar",
    category: "fonts",
    trigger: "level",
    threshold: 27,
    items: ["sigmar"],
    description: "Reach Level 27",
  },
  {
    id: "monoton",
    category: "fonts",
    trigger: "level",
    threshold: 28,
    items: ["monoton"],
    description: "Reach Level 28",
  },
  {
    id: "shrikhand",
    category: "fonts",
    trigger: "level",
    threshold: 29,
    items: ["shrikhand"],
    description: "Reach Level 29",
  },
  {
    id: "stix_two",
    category: "fonts",
    trigger: "level",
    threshold: 30,
    items: ["stix_two"],
    description: "Reach Level 30",
  },
  {
    id: "knewave",
    category: "fonts",
    trigger: "level",
    threshold: 31,
    items: ["knewave"],
    description: "Reach Level 31",
  },
  {
    id: "creepster",
    category: "fonts",
    trigger: "level",
    threshold: 32,
    items: ["creepster"],
    description: "Reach Level 32",
  },
  {
    id: "abril_fatface",
    category: "fonts",
    trigger: "level",
    threshold: 33,
    items: ["abril_fatface"],
    description: "Reach Level 33",
  },
  {
    id: "stick_no_bills",
    category: "fonts",
    trigger: "level",
    threshold: 34,
    items: ["stick_no_bills"],
    description: "Reach Level 34",
  },
  {
    id: "tourney",
    category: "fonts",
    trigger: "level",
    threshold: 35,
    items: ["tourney"],
    description: "Reach Level 35",
  },
  {
    id: "bungee_shade",
    category: "fonts",
    trigger: "level",
    threshold: 36,
    items: ["bungee_shade"],
    description: "Reach Level 36",
  },
  {
    id: "dela_gothic_one",
    category: "fonts",
    trigger: "level",
    threshold: 37,
    items: ["dela_gothic_one"],
    description: "Reach Level 37",
  },
  {
    id: "righteous",
    category: "fonts",
    trigger: "level",
    threshold: 38,
    items: ["righteous"],
    description: "Reach Level 38",
  },
  {
    id: "reem_kufi_fun",
    category: "fonts",
    trigger: "level",
    threshold: 39,
    items: ["reem_kufi_fun"],
    description: "Reach Level 39",
  },
  {
    id: "emblema_one",
    category: "fonts",
    trigger: "level",
    threshold: 40,
    items: ["emblema_one"],
    description: "Reach Level 40",
  },
  {
    id: "ranchers",
    category: "fonts",
    trigger: "level",
    threshold: 41,
    items: ["ranchers"],
    description: "Reach Level 41",
  },
  {
    id: "fascinate_inline",
    category: "fonts",
    trigger: "level",
    threshold: 42,
    items: ["fascinate_inline"],
    description: "Reach Level 42",
  },
  // 43–44: intentional gap (breathing room before milestone)
  {
    id: "foldit",
    category: "fonts",
    trigger: "level",
    threshold: 45,
    items: ["foldit"],
    description: "Reach Level 45",
  },
  {
    id: "orbitron",
    category: "fonts",
    trigger: "level",
    threshold: 46,
    items: ["orbitron"],
    description: "Reach Level 46",
  },
  {
    id: "pixelify_sans",
    category: "fonts",
    trigger: "level",
    threshold: 47,
    items: ["pixelify_sans"],
    description: "Reach Level 47",
  },
  {
    id: "shojumaru",
    category: "fonts",
    trigger: "level",
    threshold: 48,
    items: ["shojumaru"],
    description: "Reach Level 48",
  },
  {
    id: "freckle_face",
    category: "fonts",
    trigger: "level",
    threshold: 49,
    items: ["freckle_face"],
    description: "Reach Level 49",
  },
  {
    id: "vt323",
    category: "fonts",
    trigger: "level",
    threshold: 50,
    items: ["vt323"],
    description: "Reach Level 50",
  },
  {
    id: "wallpoet",
    category: "fonts",
    trigger: "level",
    threshold: 51,
    items: ["wallpoet"],
    description: "Reach Level 51",
  },
  {
    id: "nosifer",
    category: "fonts",
    trigger: "level",
    threshold: 52,
    items: ["nosifer"],
    description: "Reach Level 52",
  },
  {
    id: "moirai_one",
    category: "fonts",
    trigger: "level",
    threshold: 53,
    items: ["moirai_one"],
    description: "Reach Level 53",
  },
  // 54: intentional gap
  {
    id: "bitcount_ink",
    category: "fonts",
    trigger: "level",
    threshold: 55,
    items: ["bitcount_ink"],
    description: "Reach Level 55",
  },
  {
    id: "syncopate",
    category: "fonts",
    trigger: "level",
    threshold: 56,
    items: ["syncopate"],
    description: "Reach Level 56",
  },
  {
    id: "black_ops_one",
    category: "fonts",
    trigger: "level",
    threshold: 57,
    items: ["black_ops_one"],
    description: "Reach Level 57",
  },
  {
    id: "griffy",
    category: "fonts",
    trigger: "level",
    threshold: 58,
    items: ["griffy"],
    description: "Reach Level 58",
  },
  {
    id: "teko",
    category: "fonts",
    trigger: "level",
    threshold: 59,
    items: ["teko"],
    description: "Reach Level 59",
  },
  {
    id: "rubik_glitch",
    category: "fonts",
    trigger: "level",
    threshold: 60,
    items: ["rubik_glitch"],
    description: "Reach Level 60",
  },
  // 61–64: intentional gap
  {
    id: "bebas_neue",
    category: "fonts",
    trigger: "level",
    threshold: 61,
    items: ["bebas_neue"],
    description: "Reach Level 61",
  },
  {
    id: "honk",
    category: "fonts",
    trigger: "level",
    threshold: 65,
    items: ["honk"],
    description: "Reach Level 65",
  },

  {
    id: "rubik_doodle_shadow",
    category: "fonts",
    trigger: "level",
    threshold: 67,
    items: ["rubik_doodle_shadow"],
    description: "Reach Level 67",
  },

  {
    id: "rubik_spray_paint",
    category: "fonts",
    trigger: "level",
    threshold: 69,
    items: ["rubik_spray_paint"],
    description: "Reach Level 69",
  },

  {
    id: "rubik_dirt",
    category: "fonts",
    trigger: "level",
    threshold: 71,
    items: ["rubik_dirt"],
    description: "Reach Level 71",
  },

  {
    id: "kablammo",
    category: "fonts",
    trigger: "level",
    threshold: 73,
    items: ["kablammo"],
    description: "Reach Level 73",
  },
  {
    id: "kalnia_glaze",
    category: "fonts",
    trigger: "level",
    threshold: 75,
    items: ["kalnia_glaze"],
    description: "Reach Level 75",
  },
  {
    id: "unifraktur",
    category: "fonts",
    trigger: "level",
    threshold: 77,
    items: ["unifraktur"],
    description: "Reach Level 77",
  },
  {
    id: "sour_gummy",
    category: "fonts",
    trigger: "level",
    threshold: 79,
    items: ["sour_gummy"],
    description: "Reach Level 79",
  },
  {
    id: "rubik_puddles",
    category: "fonts",
    trigger: "level",
    threshold: 81,
    items: ["rubik_puddles"],
    description: "Reach Level 81",
  },
  {
    id: "rock_salt",
    category: "fonts",
    trigger: "level",
    threshold: 83,
    items: ["rock_salt"],
    description: "Reach Level 83",
  },
  // 76–84: intentional gap (prestige desert before pinnacle)
  {
    id: "sixtyfour_convergence",
    category: "fonts",
    trigger: "level",
    threshold: 85,
    items: ["sixtyfour_convergence"],
    description: "Reach Level 85",
  },

  // ── TOTAL HOURS (totalMinutes) ────────────────────────────────────────────────

  {
    id: "typewriter_pro",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 3000,
    items: ["typewriter_pro"],
    description: "Study 50 total hours",
  },
  {
    id: "josefin_slab",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 4500,
    items: ["josefin_slab"],
    description: "Study 75 total hours",
  },
  {
    id: "climate_crisis",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 5400,
    items: ["climate_crisis"],
    description: "Study 90 total hours",
  },
  {
    id: "playfair_display",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 6000,
    items: ["playfair_display"],
    description: "Study 100 total hours",
  },
  {
    id: "fira_code",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 9000,
    items: ["fira_code"],
    description: "Study 150 total hours",
  },
  {
    id: "major_mono",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 12000,
    items: ["major_mono"],
    description: "Study 200 total hours",
  },
  {
    id: "dm_serif",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 15000,
    items: ["dm_serif"],
    description: "Study 250 total hours",
  },
  {
    id: "instrument_serif",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 30000,
    items: ["instrument_serif"],
    description: "Study 500 total hours",
  },
  {
    id: "syne_tactical",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 45000,
    items: ["syne_tactical"],
    description: "Study 750 total hours",
  },
  {
    id: "bungee_tint",
    category: "fonts",
    trigger: "totalMinutes",
    threshold: 60000,
    items: ["bungee_tint"],
    description: "Study 1000 total hours",
  },

  // ── WEEKLY SPRINTS (weeklyMinutes) ────────────────────────────────────────────
  {
    id: "retro_pixel",
    category: "fonts",
    trigger: "weeklyMinutes",
    threshold: 2100,
    items: ["retro_pixel"],
    description: "Study 35 hrs in a week",
  },
  {
    id: "faster_one",
    category: "fonts",
    trigger: "weeklyMinutes",
    threshold: 2700,
    items: ["faster_one"],
    description: "Study 45 hrs in a week",
  },
  {
    id: "nabla",
    category: "fonts",
    trigger: "weeklyMinutes",
    threshold: 3300,
    items: ["nabla"],
    description: "Study 55 hrs in a week",
  },

  // ── MONTHLY SPRINTS (monthlyMinutes) ─────────────────────────────────────────
  {
    id: "bangers",
    category: "fonts",
    trigger: "monthlyMinutes",
    threshold: 6600,
    items: ["bangers"],
    description: "Study 110 hrs in a month",
  },
  {
    id: "silkscreen",
    category: "fonts",
    trigger: "monthlyMinutes",
    threshold: 10200,
    items: ["silkscreen"],
    description: "Study 170 hrs in a month",
  },
  {
    id: "bungee_spice",
    category: "fonts",
    trigger: "monthlyMinutes",
    threshold: 13800,
    items: ["bungee_spice"],
    description: "Study 230 hrs in a month",
  },

  // ════════════════════════════════════════
  // RINGS — Progress Rewards
  // ════════════════════════════════════════
  {
    id: "slate_outline",
    category: "rings",
    trigger: "level",
    threshold: 3,
    items: ["slate_outline"],
    description: "Reach Level 3",
  },
  {
    id: "ring_bronze_unlock",
    category: "rings",
    trigger: "level",
    threshold: 6,
    items: ["ring_bronze"],
    description: "Reach Level 6 — Bronze Ring",
  },
  {
    id: "ring_silver_unlock",
    category: "rings",
    trigger: "level",
    threshold: 8,
    items: ["ring_silver"],
    description: "Reach Level 8 — Silver Ring",
  },
  {
    id: "ring_gold_unlock",
    category: "rings",
    trigger: "level",
    threshold: 10,
    items: ["ring_gold"],
    description: "Reach Level 10 — Gold Ring",
  },
  {
    id: "ring_ruby_unlock",
    category: "rings",
    trigger: "level",
    threshold: 12,
    items: ["ring_ruby"],
    description: "Reach Level 12 — Ruby Ring",
  },
  {
    id: "ring_sapphire_unlock",
    category: "rings",
    trigger: "level",
    threshold: 14,
    items: ["ring_sapphire"],
    description: "Reach Level 14 — Sapphire Ring",
  },
  {
    id: "ring_emerald_unlock",
    category: "rings",
    trigger: "level",
    threshold: 16,
    items: ["ring_emerald"],
    description: "Reach Level 16 — Emerald Ring",
  },
  {
    id: "ring_amethyst_unlock",
    category: "rings",
    trigger: "level",
    threshold: 18,
    items: ["ring_amethyst"],
    description: "Reach Level 18 — Amethyst Ring",
  },
  {
    id: "ring_obsidian_unlock",
    category: "rings",
    trigger: "level",
    threshold: 20,
    items: ["ring_obsidian"],
    description: "Reach Level 20 — Obsidian Ring",
  },
  {
    id: "ring_ivory_unlock",
    category: "rings",
    trigger: "level",
    threshold: 22,
    items: ["ring_ivory"],
    description: "Reach Level 22 — Ivory Ring",
  },
  {
    id: "ring_rose_unlock",
    category: "rings",
    trigger: "level",
    threshold: 24,
    items: ["ring_rose"],
    description: "Reach Level 24 — Rose Ring",
  },

  // ── Tier 2: Single-color soft glow (Level 15–35) ──
  {
    id: "neon_halo_unlock",
    category: "rings",
    trigger: "level",
    threshold: 28,
    items: ["neon_halo_ring"],
    description: "Reach Level 28",
  },
  {
    id: "jade_glow_unlock",
    category: "rings",
    trigger: "level",
    threshold: 30,
    items: ["jade_glow"],
    description: "Reach Level 30",
  },
  {
    id: "frozen_crystal",
    category: "rings",
    trigger: "level",
    threshold: 32,
    items: ["frozen_crystal"],
    description: "Reach Level 32",
  },
  {
    id: "rose_quartz",
    category: "rings",
    trigger: "level",
    threshold: 34,
    items: ["rose_quartz"],
    description: "Reach Level 34",
  },
  {
    id: "scholars_glow_unlock",
    category: "rings",
    trigger: "level",
    threshold: 36,
    items: ["scholars_glow"],
    description: "Reach Level 36",
  },
  {
    id: "copper_coil",
    category: "rings",
    trigger: "level",
    threshold: 38,
    items: ["copper_coil"],
    description: "Reach Level 38",
  },
  {
    id: "lavender_drift",
    category: "rings",
    trigger: "level",
    threshold: 40,
    items: ["lavender_drift"],
    description: "Reach Level 40",
  },
  {
    id: "blood_moon_unlock",
    category: "rings",
    trigger: "level",
    threshold: 42,
    items: ["blood_moon"],
    description: "Reach Level 42",
  },
  {
    id: "twilight_band",
    category: "rings",
    trigger: "level",
    threshold: 44,
    items: ["twilight_band"],
    description: "Reach Level 44",
  },
  {
    id: "nature_pack",
    category: "rings",
    trigger: "level",
    threshold: 46,
    items: ["ivy_league"],
    description: "Reach Level 46",
  },
  {
    id: "spectral_shift",
    category: "rings",
    trigger: "level",
    threshold: 48,
    items: ["spectral_shift"],
    description: "Reach Level 48",
  },
  {
    id: "thunder_strike_unlock",
    category: "rings",
    trigger: "level",
    threshold: 50,
    items: ["thunder_strike"],
    description: "Reach Level 50",
  },

  // ── Tier 3: Dual-color / color-cycling (Level 40–60) ──
  {
    id: "prism_spin",
    category: "rings",
    trigger: "level",
    threshold: 55,
    items: ["prism_spin"],
    description: "Reach Level 55",
  },
  {
    id: "seafoam_wave",
    category: "rings",
    trigger: "level",
    threshold: 57,
    items: ["seafoam_wave"],
    description: "Reach Level 57",
  },

  {
    id: "diamond_edge",
    category: "rings",
    trigger: "level",
    threshold: 59,
    items: ["diamond_edge"],
    description: "Reach Level 59",
  },
  {
    id: "void_static",
    category: "rings",
    trigger: "level",
    threshold: 61,
    items: ["void_static"],
    description: "Reach Level 61",
  },
  {
    id: "cosmic_dust",
    category: "rings",
    trigger: "level",
    threshold: 63,
    items: ["cosmic_dust"],
    description: "Reach Level 63",
  },

  // ── Tier 4: Complex / intense (Level 65–80) ──
  {
    id: "zen_blossom_unlock",
    category: "rings",
    trigger: "level",
    threshold: 65,
    items: ["zen_blossom"],
    description: "Reach Level 65",
  },
  {
    id: "abyssal_unlock",
    category: "rings",
    trigger: "level",
    threshold: 67,
    items: ["abyssal"],
    description: "Reach Level 67",
  },
  {
    id: "eternal_flame",
    category: "rings",
    trigger: "level",
    threshold: 69,
    items: ["eternal_flame"],
    description: "Reach Level 69",
  },
  {
    id: "celestial_unlock",
    category: "rings",
    trigger: "level",
    threshold: 71,
    items: ["celestial_orbit"],
    description: "Reach Level 71",
  },
  {
    id: "phantom_drift",
    category: "rings",
    trigger: "level",
    threshold: 73,
    items: ["phantom_drift"],
    description: "Reach Level 73",
  },
  {
    id: "void_smoke_unlock",
    category: "rings",
    trigger: "level",
    threshold: 75,
    items: ["void_smoke"],
    description: "Reach Level 75",
  },

  // ── Tier 5: Elite (Level 85–100) ──
  {
    id: "magma_flow_unlock",
    category: "rings",
    trigger: "level",
    threshold: 77,
    items: ["magma_flow"],
    description: "Reach Level 77",
  },
  {
    id: "cyber_neon_unlock",
    category: "rings",
    trigger: "level",
    threshold: 79,
    items: ["cyber_neon_pulse"],
    description: "Reach Level 79",
  },
  {
    id: "quantum_flux",
    category: "rings",
    trigger: "level",
    threshold: 81,
    items: ["quantum_flux"],
    description: "Reach Level 81",
  },
  {
    id: "crimson_tide_unlock",
    category: "rings",
    trigger: "level",
    threshold: 83,
    items: ["crimson_tide"],
    description: "Reach Level 83",
  },

  // ── Total Hours ──
  {
    id: "sakura_250h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 15000,
    items: ["sakura_ring"],
    description: "Study 250 total hours",
  },
  {
    id: "moonbeam_350h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 21000,
    items: ["moonbeam"],
    description: "Study 350 total hours",
  },
  {
    id: "amber_sunset_500h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 30000,
    items: ["amber_sunset"],
    description: "Study 500 total hours",
  },
  {
    id: "deep_ocean_150h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 36000,
    items: ["deep_ocean_ring"],
    description: "Study 600 total hours",
  },
  {
    id: "aurora_750h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 45000,
    items: ["aurora_borealis"],
    description: "Study 750 total hours",
  },
  {
    id: "starfield_500h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 51000,
    items: ["starfield_ring"],
    description: "Study 850 total hours",
  },
  {
    id: "singularity_750h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 60000,
    items: ["singularity_ring"],
    description: "Study 1000 total hours",
  },
  {
    id: "solar_flare_1000h",
    category: "rings",
    trigger: "totalMinutes",
    threshold: 90000,
    items: ["solar_flare"],
    description: "Study 1500 total hours",
  },

  // ── Weekly Sprints (high intensity, temporary) ──
  {
    id: "grindstone_30h_wk",
    category: "rings",
    trigger: "weeklyMinutes",
    threshold: 1800,
    items: ["grindstone_ring"],
    description: "Study 30 hours in a week",
  },
  {
    id: "overdrive_40h_wk",
    category: "rings",
    trigger: "weeklyMinutes",
    threshold: 2400,
    items: ["overdrive_ring"],
    description: "Study 40 hours in a week",
  },
  {
    id: "neon_circuit_60h_wk",
    category: "rings",
    trigger: "weeklyMinutes",
    threshold: 3600,
    items: ["neon_circuit"],
    description: "Study 60 hours in a week",
  },
  {
    id: "electric_70h_wk",
    category: "rings",
    trigger: "weeklyMinutes",
    threshold: 4200,
    items: ["electric_pulse"],
    description: "Study 70 hours in a week",
  },

  // ── Monthly Sprints (consistency, temporary) ──
  {
    id: "persistence_120h_mo",
    category: "rings",
    trigger: "monthlyMinutes",
    threshold: 7200,
    items: ["persistence_ring"],
    description: "Study 120 hours in a month",
  },
  {
    id: "marathon_180h_mo",
    category: "rings",
    trigger: "monthlyMinutes",
    threshold: 10800,
    items: ["marathon_ring"],
    description: "Study 180 hours in a month",
  },
  {
    id: "titan_240h_mo",
    category: "rings",
    trigger: "monthlyMinutes",
    threshold: 14400,
    items: ["titan_ring"],
    description: "Study 240 hours in a month",
  },

  {
    id: "medicine_ring",
    category: "rings",
    trigger: "level",
    threshold: 5,
    items: ["medicine_ring"],
    description: "Reach Level 5",
  },
  {
    id: "law_ring",
    category: "rings",
    trigger: "level",
    threshold: 7,
    items: ["law_ring"],
    description: "Reach Level 7",
  },
  {
    id: "engineering_ring",
    category: "rings",
    trigger: "level",
    threshold: 9,
    items: ["engineering_ring"],
    description: "Reach Level 9",
  },
  {
    id: "science_ring",
    category: "rings",
    trigger: "level",
    threshold: 11,
    items: ["science_ring"],
    description: "Reach Level 11",
  },
  {
    id: "arts_ring",
    category: "rings",
    trigger: "level",
    threshold: 13,
    items: ["arts_ring"],
    description: "Reach Level 13",
  },
  {
    id: "economics_ring",
    category: "rings",
    trigger: "level",
    threshold: 15,
    items: ["economics_ring"],
    description: "Reach Level 15",
  },
  {
    id: "music_ring",
    category: "rings",
    trigger: "level",
    threshold: 17,
    items: ["music_ring"],
    description: "Reach Level 17",
  },
  {
    id: "dentistry_ring",
    category: "rings",
    trigger: "level",
    threshold: 19,
    items: ["dentistry_ring"],
    description: "Reach Level 19",
  },
  {
    id: "sports_ring",
    category: "rings",
    trigger: "level",
    threshold: 21,
    items: ["sports_ring"],
    description: "Reach Level 21",
  },
  {
    id: "psychology_ring",
    category: "rings",
    trigger: "level",
    threshold: 23,
    items: ["psychology_ring"],
    description: "Reach Level 23",
  },
  {
    id: "veterinary_ring",
    category: "rings",
    trigger: "level",
    threshold: 25,
    items: ["veterinary_ring"],
    description: "Reach Level 25",
  },

  // ════════════════════════════════════════
  // OVERLAYS — Progress Rewards
  // ════════════════════════════════════════
  {
    id: "snowfall",
    category: "overlays",
    trigger: "level",
    threshold: 15,
    items: ["snowfall"],
    description: "Reach Level 15",
  },
  {
    id: "fireflies",
    category: "overlays",
    trigger: "level",
    threshold: 22,
    items: ["fireflies"],
    description: "Reach Level 22",
  },
  {
    id: "northern_lights",
    category: "overlays",
    trigger: "level",
    threshold: 45,
    items: ["northern_lights"],
    description: "Reach Level 45",
  },
  {
    id: "star_rain",
    category: "overlays",
    trigger: "level",
    threshold: 70,
    items: ["star_rain"],
    description: "Reach Level 70",
  },
  {
    id: "dust_particles",
    category: "overlays",
    trigger: "totalMinutes",
    threshold: 3000,
    items: ["dust_particles"],
    description: "Study 50 total hours",
  },
  {
    id: "rainy_window",
    category: "overlays",
    trigger: "totalMinutes",
    threshold: 9000,
    items: ["rainy_window"],
    description: "Study 150 total hours",
  },
  {
    id: "sakura_breeze",
    category: "overlays",
    trigger: "totalMinutes",
    threshold: 18000,
    items: ["sakura_breeze"],
    description: "Study 300 total hours",
  },
  {
    id: "falling_leaves",
    category: "overlays",
    trigger: "totalMinutes",
    threshold: 12000,
    items: ["falling_leaves"],
    description: "Study 200 total hours",
  },
  {
    id: "fog_drift",
    category: "overlays",
    trigger: "totalMinutes",
    threshold: 24000,
    items: ["fog_drift"],
    description: "Study 400 total hours",
  },
  {
    id: "nebula_mist",
    category: "overlays",
    trigger: "totalMinutes",
    threshold: 6000,
    items: ["nebula_mist"],
    description: "Study 100 total hours",
  },
  {
    id: "confetti_burst",
    category: "overlays",
    trigger: "totalMinutes",
    threshold: 60000,
    items: ["confetti_burst"],
    description: "Study 1000 total hours",
  },
  // Sprint overlays
  {
    id: "matrix_code",
    category: "overlays",
    trigger: "weeklyMinutes",
    threshold: 1200,
    items: ["matrix_code"],
    description: "Study 20 hours in a week",
  },
  {
    id: "ember_storm",
    category: "overlays",
    trigger: "weeklyMinutes",
    threshold: 1800,
    items: ["ember_storm"],
    description: "Study 30 hours in a week",
  },
  {
    id: "crystal_frost",
    category: "overlays",
    trigger: "monthlyMinutes",
    threshold: 4800,
    items: ["crystal_frost"],
    description: "Study 80 hours in a month",
  },

  // ════════════════════════════════════════
  // NAMEPLATES — Progress Rewards
  // ════════════════════════════════════════
  {
    id: "np_golden_ribbon",
    category: "nameplates",
    trigger: "level",
    threshold: 5,
    items: ["golden_ribbon"],
    description: "Reach Level 5",
  },
  {
    id: "np_gothic_parchment",
    category: "nameplates",
    trigger: "level",
    threshold: 15,
    items: ["gothic_parchment"],
    description: "Reach Level 15",
  },
  {
    id: "np_cyber_hud",
    category: "nameplates",
    trigger: "level",
    threshold: 25,
    items: ["cyber_hud"],
    description: "Reach Level 25",
  },
  {
    id: "np_prismatic",
    category: "nameplates",
    trigger: "level",
    threshold: 40,
    items: ["prismatic"],
    description: "Reach Level 40",
  },
  {
    id: "np_obsidian_seal",
    category: "nameplates",
    trigger: "level",
    threshold: 60,
    items: ["obsidian_seal"],
    description: "Reach Level 60",
  },
  {
    id: "np_celestial_script",
    category: "nameplates",
    trigger: "level",
    threshold: 80,
    items: ["celestial_script"],
    description: "Reach Level 80",
  },
  {
    id: "np_scholar_crest",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 6000,
    items: ["scholar_crest"],
    description: "Study 100 total hours",
  },
  {
    id: "np_inferno_tag",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 1800,
    items: ["inferno_tag"],
    description: "Study 30 hours in a week",
  },
  // ── NAMEPLATES: Level-gated ───────────────────────────────────────────────
  {
    id: "np_sakura_veil",
    category: "nameplates",
    trigger: "level",
    threshold: 10,
    items: ["sakura_veil"],
    description: "Reach Level 10",
  },
  {
    id: "np_ocean_drift",
    category: "nameplates",
    trigger: "level",
    threshold: 17,
    items: ["ocean_drift"],
    description: "Reach Level 17",
  },
  {
    id: "np_deep_void",
    category: "nameplates",
    trigger: "level",
    threshold: 20,
    items: ["deep_void_np"],
    description: "Reach Level 20",
  },
  {
    id: "np_vaporwave_grid",
    category: "nameplates",
    trigger: "level",
    threshold: 30,
    items: ["vaporwave_grid"],
    description: "Reach Level 30",
  },
  {
    id: "np_rust_faction",
    category: "nameplates",
    trigger: "level",
    threshold: 38,
    items: ["rust_faction"],
    description: "Reach Level 38",
  },
  // {
  //   id: "np_angel_protocol",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 45,
  //   items: ["angel_protocol"],
  //   description: "Reach Level 45",
  // },
  {
    id: "np_phantom_garden",
    category: "nameplates",
    trigger: "level",
    threshold: 52,
    items: ["phantom_garden"],
    description: "Reach Level 52",
  },
  {
    id: "np_ember_forge",
    category: "nameplates",
    trigger: "level",
    threshold: 57,
    items: ["ember_forge"],
    description: "Reach Level 57",
  },
  {
    id: "np_glitch_manifest",
    category: "nameplates",
    trigger: "level",
    threshold: 62,
    items: ["glitch_manifest"],
    description: "Reach Level 62",
  },
  {
    id: "np_diamond_rain",
    category: "nameplates",
    trigger: "level",
    threshold: 70,
    items: ["diamond_rain"],
    description: "Reach Level 70",
  },
  {
    id: "np_neon_kanji",
    category: "nameplates",
    trigger: "level",
    threshold: 75,
    items: ["neon_kanji"],
    description: "Reach Level 75",
  },
  // {
  //   id: "np_abyssal_rift",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 85,
  //   items: ["abyssal_rift_np"],
  //   description: "Reach Level 85",
  // },

  // ── NAMEPLATES: Hour-gated ────────────────────────────────────────────────
  {
    id: "np_lava_core",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 4500,
    items: ["lava_core"],
    description: "Study 75 total hours",
  },
  {
    id: "np_copper_verdigris",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 9000,
    items: ["copper_verdigris"],
    description: "Study 150 total hours",
  },
  {
    id: "np_holographic",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 12000,
    items: ["holographic_prism"],
    description: "Study 200 total hours",
  },
  {
    id: "np_void_hex",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 18000,
    items: ["void_hex"],
    description: "Study 300 total hours",
  },
  {
    id: "np_obsidian_crown",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 30000,
    items: ["obsidian_crown"],
    description: "Study 500 total hours",
  },

  // ── NAMEPLATES: Weekly sprints ────────────────────────────────────────────
  {
    id: "np_toxic_sludge",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 1200,
    items: ["toxic_sludge"],
    description: "Study 20 hours in a week",
  },
  {
    id: "np_thunder_roll",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 1500,
    items: ["thunder_roll_np"],
    description: "Study 25 hours in a week",
  },
  {
    id: "np_neon_outrun",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 2400,
    items: ["neon_outrun"],
    description: "Study 40 hours in a week",
  },

  // ── NAMEPLATES: Monthly sprints ───────────────────────────────────────────
  {
    id: "np_sundown",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 3000,
    items: ["sundown_protocol"],
    description: "Study 50 hours in a month",
  },
  {
    id: "np_arctic_circuit",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 4800,
    items: ["arctic_circuit"],
    description: "Study 80 hours in a month",
  },
  // ── 20 NEW NAMEPLATE RULES ────────────────────────────────────────────────

  // Level-gated (fill gaps in the ladder, max stays at 85)
  {
    id: "np_frost_weave",
    category: "nameplates",
    trigger: "level",
    threshold: 7,
    items: ["frost_weave"],
    description: "Reach Level 7",
  },
  // {
  //   id: "np_golden_dusk",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 12,
  //   items: ["golden_dusk"],
  //   description: "Reach Level 12",
  // },
  {
    id: "np_rose_ash",
    category: "nameplates",
    trigger: "level",
    threshold: 22,
    items: ["rose_ash_np"],
    description: "Reach Level 22",
  },
  {
    id: "np_northern_pine",
    category: "nameplates",
    trigger: "level",
    threshold: 27,
    items: ["northern_pine_np"],
    description: "Reach Level 27",
  },
  {
    id: "np_midnight_oil",
    category: "nameplates",
    trigger: "level",
    threshold: 33,
    items: ["midnight_oil_np"],
    description: "Reach Level 33",
  },
  // {
  //   id: "np_iris_bloom",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 35,
  //   items: ["iris_bloom_np"],
  //   description: "Reach Level 35",
  // },
  {
    id: "np_lunar_moth",
    category: "nameplates",
    trigger: "level",
    threshold: 42,
    items: ["lunar_moth_np"],
    description: "Reach Level 42",
  },
  {
    id: "np_koi_pond",
    category: "nameplates",
    trigger: "level",
    threshold: 48,
    items: ["koi_pond_np"],
    description: "Reach Level 48",
  },
  {
    id: "np_eclipse_core",
    category: "nameplates",
    trigger: "level",
    threshold: 55,
    items: ["eclipse_core_np"],
    description: "Reach Level 55",
  },
  {
    id: "np_plasma_vent",
    category: "nameplates",
    trigger: "level",
    threshold: 65,
    items: ["plasma_vent_np"],
    description: "Reach Level 65",
  },

  // Hour-gated
  {
    id: "np_desert_storm",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 3000,
    items: ["desert_storm_np"],
    description: "Study 50 total hours",
  },
  {
    id: "np_solar_wind",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 6000,
    items: ["solar_wind_np"],
    description: "Study 100 total hours",
  },
  {
    id: "np_aurora_silk",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 15000,
    items: ["aurora_silk_np"],
    description: "Study 250 total hours",
  },
  {
    id: "np_quicksilver",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 24000,
    items: ["quicksilver_np"],
    description: "Study 400 total hours",
  },

  // Weekly sprints
  {
    id: "np_hyperspace",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 900,
    items: ["hyperspace_np"],
    description: "Study 15 hours in a week",
  },
  {
    id: "np_jade_matrix",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 1800,
    items: ["jade_matrix_np"],
    description: "Study 30 hours in a week",
  },
  {
    id: "np_blood_moon",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 2700,
    items: ["blood_moon_np"],
    description: "Study 45 hours in a week",
  },

  // Monthly sprints
  // {
  //   id: "np_cyber_lotus",
  //   category: "nameplates",
  //   trigger: "monthlyMinutes",
  //   threshold: 1800,
  //   items: ["cyber_lotus_np"],
  //   description: "Study 30 hours in a month",
  // },
  {
    id: "np_tempest_eye",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 3600,
    items: ["tempest_eye_np"],
    description: "Study 60 hours in a month",
  },
  {
    id: "np_obsidian_mirror",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 6000,
    items: ["obsidian_mirror_np"],
    description: "Study 100 hours in a month",
  },
  // Level-gated
  {
    id: "np_sage_mist",
    category: "nameplates",
    trigger: "level",
    threshold: 9,
    items: ["sage_mist_np"],
    description: "Reach Level 9",
  },
  {
    id: "np_coral_tide",
    category: "nameplates",
    trigger: "level",
    threshold: 13,
    items: ["coral_tide_np"],
    description: "Reach Level 13",
  },
  {
    id: "np_velvet_noir",
    category: "nameplates",
    trigger: "level",
    threshold: 19,
    items: ["velvet_noir_np"],
    description: "Reach Level 19",
  },
  {
    id: "np_twilight_spire",
    category: "nameplates",
    trigger: "level",
    threshold: 24,
    items: ["twilight_spire_np"],
    description: "Reach Level 24",
  },
  {
    id: "np_copper_storm",
    category: "nameplates",
    trigger: "level",
    threshold: 29,
    items: ["copper_storm_np"],
    description: "Reach Level 29",
  },
  {
    id: "np_bioluminescent",
    category: "nameplates",
    trigger: "level",
    threshold: 36,
    items: ["bioluminescent_np"],
    description: "Reach Level 36",
  },
  // {
  //   id: "np_ink_bloom",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 43,
  //   items: ["ink_bloom_np"],
  //   description: "Reach Level 43",
  // },
  {
    id: "np_crystal_cave",
    category: "nameplates",
    trigger: "level",
    threshold: 50,
    items: ["crystal_cave_np"],
    description: "Reach Level 50",
  },
  {
    id: "np_solar_loop",
    category: "nameplates",
    trigger: "level",
    threshold: 58,
    items: ["solar_loop_np"],
    description: "Reach Level 58",
  },
  {
    id: "np_phantom_tide",
    category: "nameplates",
    trigger: "level",
    threshold: 67,
    items: ["phantom_tide_np"],
    description: "Reach Level 67",
  },
  {
    id: "np_neon_drip",
    category: "nameplates",
    trigger: "level",
    threshold: 78,
    items: ["neon_drip_np"],
    description: "Reach Level 78",
  },

  // Hour-gated
  {
    id: "np_amber_resin",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 1800,
    items: ["amber_resin_np"],
    description: "Study 30 total hours",
  },
  {
    id: "np_frozen_tundra",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 7500,
    items: ["frozen_tundra_np"],
    description: "Study 125 total hours",
  },
  {
    id: "np_cosmic_string",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 21000,
    items: ["cosmic_string_np"],
    description: "Study 350 total hours",
  },
  {
    id: "np_gold_leaf",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 36000,
    items: ["gold_leaf_np"],
    description: "Study 600 total hours",
  },

  // Weekly sprints
  {
    id: "np_crimson_lattice",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 600,
    items: ["crimson_lattice_np"],
    description: "Study 10 hours in a week",
  },
  {
    id: "np_ember_drift",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 2100,
    items: ["ember_drift_np"],
    description: "Study 35 hours in a week",
  },

  // Monthly sprints
  // {
  //   id: "np_velvet_storm",
  //   category: "nameplates",
  //   trigger: "monthlyMinutes",
  //   threshold: 1200,
  //   items: ["velvet_storm_np"],
  //   description: "Study 20 hours in a month",
  // },
  {
    id: "np_midnight_prism",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 2400,
    items: ["midnight_prism_np"],
    description: "Study 40 hours in a month",
  },
  // {
  //   id: "np_phosphene",
  //   category: "nameplates",
  //   trigger: "monthlyMinutes",
  //   threshold: 7500,
  //   items: ["phosphene_np"],
  //   description: "Study 125 hours in a month",
  // },
  // ── Simple Tier ───────────────────────────────────────────────────────────────
  // {
  //   id: "np_mint_haze",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 2,
  //   items: ["mint_haze_np"],
  //   description: "Reach Level 2",
  // },
  // {
  //   id: "np_lavender_mist",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 3,
  //   items: ["lavender_mist_np"],
  //   description: "Reach Level 3",
  // },
  // {
  //   id: "np_peach_blush",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 4,
  //   items: ["peach_blush_np"],
  //   description: "Reach Level 4",
  // },
  // {
  //   id: "np_slate_fog",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 6,
  //   items: ["slate_fog_np"],
  //   description: "Reach Level 6",
  // },
  // {
  //   id: "np_cobalt_surge",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 8,
  //   items: ["cobalt_surge_np"],
  //   description: "Reach Level 8",
  // },
  // {
  //   id: "np_citrine_ray",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 11,
  //   items: ["citrine_ray_np"],
  //   description: "Reach Level 11",
  // },
  // {
  //   id: "np_rose_gold_veil",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 14,
  //   items: ["rose_gold_veil_np"],
  //   description: "Reach Level 14",
  // },
  // {
  //   id: "np_viridian_mist",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 16,
  //   items: ["viridian_mist_np"],
  //   description: "Reach Level 16",
  // },
  // {
  //   id: "np_amber_warmth",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 18,
  //   items: ["amber_warmth_np"],
  //   description: "Reach Level 18",
  // },
  // {
  //   id: "np_steel_sheen",
  //   category: "nameplates",
  //   trigger: "level",
  //   threshold: 21,
  //   items: ["steel_sheen_np"],
  //   description: "Reach Level 21",
  // },

  // ── Complex Tier ──────────────────────────────────────────────────────────────
  {
    id: "np_singularity",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 45000,
    items: ["singularity_np"],
    description: "Study 750 total hours",
  },
  {
    id: "np_nuclear_bloom",
    category: "nameplates",
    trigger: "level",
    threshold: 82,
    items: ["nuclear_bloom_np"],
    description: "Reach Level 82",
  },
  {
    id: "np_maelstrom",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 3600,
    items: ["maelstrom_np"],
    description: "Study 60 hours in a week",
  },
  {
    id: "np_divine_fracture",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 9000,
    items: ["divine_fracture_np"],
    description: "Study 150 hours in a month",
  },
  {
    id: "np_event_horizon",
    category: "nameplates",
    trigger: "level",
    threshold: 84,
    items: ["event_horizon_np"],
    description: "Reach Level 84",
  },
  {
    id: "np_void_collapse",
    category: "nameplates",
    trigger: "level",
    threshold: 90,
    items: ["void_collapse_np"],
    description: "Reach Level 90",
  },
  {
    id: "np_solar_coronation",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 4200, // 70 hours
    items: ["solar_coronation_np"],
    description: "Study 70 hours in a week",
  },
  {
    id: "np_abyssal_rift",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 60000, // 1000 hours
    items: ["abyssal_rift_np"],
    description: "Study 1,000 total hours",
  },
  {
    id: "np_plasma_throne",
    category: "nameplates",
    trigger: "level",
    threshold: 95,
    items: ["plasma_throne_np"],
    description: "Reach Level 95",
  },
  {
    id: "np_temporal_fracture",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 10800, // 180 hours
    items: ["temporal_fracture_np"],
    description: "Study 180 hours in a month",
  },
  {
    id: "np_glacial_obliteration",
    category: "nameplates",
    trigger: "level",
    threshold: 88,
    items: ["glacial_obliteration_np"],
    description: "Reach Level 88",
  },
  {
    id: "np_phoenix_pyre",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 72000, // 1200 hours
    items: ["phoenix_pyre_np"],
    description: "Study 1,200 total hours",
  },
  {
    id: "np_quantum_entanglement",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 4800, // 80 hours
    items: ["quantum_entanglement_np"],
    description: "Study 80 hours in a week",
  },
  {
    id: "np_infernal_gate",
    category: "nameplates",
    trigger: "level",
    threshold: 99,
    items: ["infernal_gate_np"],
    description: "Reach Level 99",
  },
  {
    id: "np_celestial_collapse",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 15000, // 250 hours
    items: ["celestial_collapse_np"],
    description: "Study 250 hours in a month",
  },
  {
    id: "np_vibrant_gold",
    category: "nameplates",
    trigger: "level",
    threshold: 40,
    items: ["vibrant_gold_np"],
    description: "Reach Level 40",
  },
  {
    id: "np_vibrant_red",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 2400, // 40 hours
    items: ["vibrant_red_np"],
    description: "Study 40 hours in a week",
  },
  {
    id: "np_vibrant_pink",
    category: "nameplates",
    trigger: "level",
    threshold: 45,
    items: ["vibrant_pink_np"],
    description: "Reach Level 45",
  },
  {
    id: "np_vibrant_blue",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 30000, // 500 hours
    items: ["vibrant_blue_np"],
    description: "Study 500 total hours",
  },
  {
    id: "np_vibrant_green",
    category: "nameplates",
    trigger: "level",
    threshold: 50,
    items: ["vibrant_green_np"],
    description: "Reach Level 50",
  },
  {
    id: "np_vibrant_violet",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 3000, // 50 hours
    items: ["vibrant_violet_np"],
    description: "Study 50 hours in a week",
  },
  {
    id: "np_vibrant_silver",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 45000, // 750 hours
    items: ["vibrant_silver_np"],
    description: "Study 750 total hours",
  },
  {
    id: "np_vibrant_cyan",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 7200, // 120 hours
    items: ["vibrant_cyan_np"],
    description: "Study 120 hours in a month",
  },
  {
    id: "np_vibrant_midnight",
    category: "nameplates",
    trigger: "level",
    threshold: 60,
    items: ["vibrant_midnight_np"],
    description: "Reach Level 60",
  },
  {
    id: "np_vibrant_yellow",
    category: "nameplates",
    trigger: "level",
    threshold: 15,
    items: ["vibrant_yellow_np"],
    description: "Reach Level 15",
  },
  {
    id: "np_vibrant_navy",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 12000, // 200 hours
    items: ["vibrant_navy_np"],
    description: "Study 200 total hours",
  },
  {
    id: "np_vibrant_bronze",
    category: "nameplates",
    trigger: "level",
    threshold: 22,
    items: ["vibrant_bronze_np"],
    description: "Reach Level 22",
  },
  {
    id: "np_vibrant_peach",
    category: "nameplates",
    trigger: "level",
    threshold: 18,
    items: ["vibrant_peach_np"],
    description: "Reach Level 18",
  },
  {
    id: "np_vibrant_lime",
    category: "nameplates",
    trigger: "weeklyMinutes",
    threshold: 2100, // 35 hours
    items: ["vibrant_lime_np"],
    description: "Study 35 hours in a week",
  },
  {
    id: "np_vibrant_darkgreen",
    category: "nameplates",
    trigger: "totalMinutes",
    threshold: 21000, // 350 hours
    items: ["vibrant_darkgreen_np"],
    description: "Study 350 total hours",
  },
  {
    id: "np_vibrant_maroon",
    category: "nameplates",
    trigger: "monthlyMinutes",
    threshold: 5400, // 90 hours
    items: ["vibrant_maroon_np"],
    description: "Study 90 hours in a month",
  },
  //──────────────────────────────────────────────────── NEW ADDITIONS  UNORGANIZED ────────────────────────────────────────────────────
];

export { UNLOCK_RULES };

export const checkUnlocks = async (user) => {
  const totalMinutes = user.totalStudyDuration || 0;
  const weeklyMinutes = user.weeklyStats?.studyDuration || 0;
  const monthlyMinutes = user.monthlyStats?.studyDuration || 0;
  const level = user.pomodoroLevel || 0;

  const getValue = (trigger) => {
    switch (trigger) {
      case "level":
        return level;
      case "totalMinutes":
        return totalMinutes;
      case "weeklyMinutes":
        return weeklyMinutes;
      case "monthlyMinutes":
        return monthlyMinutes;
      default:
        return 0;
    }
  };

  const newlyUnlocked = [];

  // Ensure nameplates array exists (migration safety)
  if (!user.inventory.nameplates) user.inventory.nameplates = [];

  for (const rule of UNLOCK_RULES) {
    if (rule.trigger === "achievement") continue;
    if (getValue(rule.trigger) < rule.threshold) continue;

    const owned = user.inventory[rule.category] || [];
    const missing = rule.items.filter((item) => !owned.includes(item));
    if (missing.length === 0) continue;

    user.inventory[rule.category].push(...missing);
    newlyUnlocked.push(...missing);
  }

  if (newlyUnlocked.length > 0) {
    user.markModified("inventory");
    await user.save();
  }

  return newlyUnlocked;
};
