export const POMODORO_PRESETS = [
  { key: "aurora", label: "Aurora Borealis", path: "/backgrounds/aurora.mp4" },
  { key: "sky", label: "Endless Sky", path: "/backgrounds/sky_man.mp4" },
  { key: "camp", label: "Camping", path: "/backgrounds/camp.mp4" },
  { key: "cabin", label: "Rainy Cabin", path: "/backgrounds/cabin.mp4" },
  { key: "dead-tree", label: "Lonely Tree", path: "/backgrounds/dead_tree.mp4" },
  { key: "cat", label: "Cat Window", path: "/backgrounds/cat_window.mp4" },
  { key: "cat3", label: "Cat Window 2", path: "/backgrounds/cat_window3.mp4" },
  { key: "lofi_snow", label: "Lofi Snow", path: "/backgrounds/lofi_snow.mp4" },
  { key: "stars", label: "Stars", path: "/backgrounds/stars.mp4" },
  { key: "piggy", label: "Piggy", path: "/backgrounds/piggy.mp4" },
  { key: "fireplace", label: "Fireplace", path: "/backgrounds/fireplace.mp4" },
  { key: "coffee_outside", label: "Coffee 1", path: "/backgrounds/coffee_outside.mp4" },
  { key: "coffee_inside", label: "Coffee 2", path: "/backgrounds/coffee_inside.mp4" },
  { key: "cafe", label: "Café", path: "/backgrounds/cafe.mp4" },
  { key: "sakura", label: "Sakura", path: "/backgrounds/sakura.jpg" },
  { key: "above_clouds", label: "Above the Clouds", path: "/backgrounds/above_clouds.mp4" },
  { key: "huskies", label: "Huskies", path: "/backgrounds/huskies.jpg" },
  { key: "milkyway", label: "Milky Way", path: "/backgrounds/milkyway.jpg" },
  { key: "universe", label: "Universe", path: "/backgrounds/universe.jpg" },
  { key: "moon", label: "Midnight Sky", path: "/backgrounds/moon.mp4" },
  { key: "river", label: "Mountain Landscape", path: "/backgrounds/river.mp4" },
  { key: "puppy", label: "Puppy", path: "/backgrounds/puppy.jpg" },
  { key: "cat_cartoon", label: "Cartoon Cat", path: "/backgrounds/cat_cartoon.mp4" },
]
